-- ============================================================================
-- Seed: biblioteca global de competências (categorias, competências, perguntas)
-- Fonte: conteúdo consolidado em docs/biblioteca-competencias.md, incluindo os
-- ajustes de texto identificados no export do cliente em 2026-08-13.
-- ============================================================================

insert into categories (id, name, description, "order", color) values
  ('bloco1', 'Execução e Produtividade', 'Avalia a capacidade de transformar planos em entregas concretas, com organização, foco e eficiência. Observa como a pessoa gerencia tempo, prioridades, prazos e volume de trabalho, garantindo constância e qualidade na execução das atividades.', 1, '#6155f5'),
  ('bloco2', 'Qualidade Técnica e Cognitiva', 'Avalia o domínio técnico, a capacidade de raciocínio, análise e resolução de problemas. Considera a atenção aos detalhes, o pensamento lógico e crítico, a clareza intelectual e a aplicação adequada do conhecimento no trabalho.', 2, '#34d399'),
  ('bloco3', 'Relação com Clientes e Stakeholders', 'Avalia como a pessoa se comunica e se relaciona com clientes, parceiros e demais partes envolvidas. Observa empatia, clareza, confiabilidade, postura profissional e a capacidade de compreender necessidades e alinhar expectativas.', 3, '#ff8d28'),
  ('bloco4', 'Relações Internas e Colaboração', 'Avalia a qualidade das relações interpessoais no ambiente interno. Considera trabalho em equipe, comunicação, empatia, disponibilidade para ajudar, respeito às diferenças e contribuição para um clima organizacional saudável.', 4, '#f472b6'),
  ('bloco5', 'Postura Profissional e Ética', 'Avalia atitudes, valores e comportamentos no exercício profissional. Observa responsabilidade, comprometimento, ética, transparência, confiabilidade e coerência entre discurso e prática no dia a dia de trabalho.', 5, '#60a5fa'),
  ('bloco6', 'Desenvolvimento, Adaptação e Futuro', 'Avalia a capacidade de aprender, adaptar-se e evoluir continuamente. Considera abertura a feedbacks, busca por desenvolvimento, flexibilidade diante de mudanças, visão de futuro e disposição para crescer junto com a organização.', 6, '#a78bfa');

do $$
declare
  comp_id uuid;
begin
  insert into competencies (category_id, name, "order") values ('bloco1', 'Agilidade', 1) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Realiza suas tarefas de forma rápida sem prejudicar a qualidade do trabalho.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Identifica problemas com rapidez.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Encontra soluções de forma eficaz e ágil.', 2);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Utiliza o tempo necessário para executar suas atividades, sem excessos.', 3);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando nos projetos mais recentes, de que forma você conduziu as entregas para cumprir os prazos e como avalia o resultado disso?', 4);
  insert into competencies (category_id, name, "order") values ('bloco1', 'Capacidade de Execução', 2) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Consegue transformar planos em ações concretas.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Utiliza adequadamente os recursos disponíveis para atingir seus objetivos.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Atua de forma sistemática para concluir o que foi planejado.', 2);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Considerando os últimos projetos, como aconteceu a passagem do planejamento para a execução e que efeito isso teve no trabalho realizado?', 3);
  insert into competencies (category_id, name, "order") values ('bloco1', 'Organização', 3) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Organiza previamente seu material e suas atividades de trabalho.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Administra bem o tempo para realizar suas tarefas.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Planeja as atividades antes de executá-las.', 2);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Define metas claras alinhadas aos objetivos estabelecidos.', 3);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Nos projetos recentes, como você estruturou e organizou seu trabalho para dar andamento às atividades e como isso impactou o processo?', 4);
  insert into competencies (category_id, name, "order") values ('bloco1', 'Planejamento', 4) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Estabelece objetivos e metas antes de iniciar suas atividades.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Planeja considerando prioridades e recursos disponíveis.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Ajusta o planejamento quando surgem mudanças.', 2);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Antecipa recursos necessários para executar suas demandas.', 3);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Ao lembrar dos últimos projetos, como você se organizou antes de iniciar as atividades e em que medida isso contribuiu para o desenvolvimento do trabalho?', 4);
  insert into competencies (category_id, name, "order") values ('bloco1', 'Priorização', 5) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Prioriza tarefas de forma eficiente.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Identifica corretamente o que é mais importante e urgente.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Nos projetos mais recentes, como você definiu o que precisava ser feito primeiro e como avalia os resultados dessa escolha?', 2);
  insert into competencies (category_id, name, "order") values ('bloco1', 'Orientação para Resultado', 6) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Estabelece metas claras e mensuráveis.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Busca maximizar produtividade e eficiência.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Monitora o progresso das atividades.', 2);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Corrige desvios que possam comprometer os resultados.', 3);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Mantém foco nas atividades prioritárias e nos prazos.', 4);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando nos projetos recentes, de que forma você acompanhou se o trabalho estava caminhando para os resultados esperados e como isso funcionou na prática?', 5);
  insert into competencies (category_id, name, "order") values ('bloco1', 'Atenção Concentrada', 7) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Mantém atenção em uma tarefa mesmo em ambientes com interferências.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Demonstra preocupação constante em executar o trabalho sem erros.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Identifica erros ou inconsistências no fluxo de atividades.', 2);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Ao longo dos últimos projetos, como foi sua experiência em manter o foco durante a execução das atividades e quais efeitos isso teve no trabalho?', 3);
  insert into competencies (category_id, name, "order") values ('bloco1', 'Detalhista', 8) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Garante precisão e qualidade em cada etapa do trabalho.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Dedica tempo necessário para revisar e corrigir detalhes.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Considerando as entregas dos últimos projetos, como você lidou com os detalhes e revisões e como isso se refletiu no resultado final?', 2);
  insert into competencies (category_id, name, "order") values ('bloco2', 'Raciocínio Lógico', 9) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Analisa informações de forma objetiva e lógica.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Resolve problemas de maneira sistemática.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Baseia decisões em evidências.', 2);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando nos últimos projetos, como você analisou as informações e chegou às decisões necessárias, e como avalia os resultados disso?', 3);
  insert into competencies (category_id, name, "order") values ('bloco2', 'Raciocínio Abstrato', 10) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Conecta ideias complexas e identifica padrões não evidentes.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Visualiza conceitos futuros e relações sistêmicas.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Ao olhar para os projetos mais recentes, como você conectou ideias e pensou em cenários possíveis para o trabalho, e quanto isso ajudou no resultado final?', 2);
  insert into competencies (category_id, name, "order") values ('bloco2', 'Capacidade Investigativa', 11) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Busca ativamente informações para compreender problemas.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Utiliza fontes variadas para aprofundar o entendimento.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Não se contenta com respostas superficiais.', 2);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Nos últimos projetos, quando surgiram dúvidas ou problemas, como você buscou informações para entender melhor a situação e como isso funcionou na prática?', 3);
  insert into competencies (category_id, name, "order") values ('bloco2', 'Senso Crítico', 12) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Questiona suposições e processos estabelecidos.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Analisa informações antes de aceitar conclusões.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando nos projetos recentes, como você questionou práticas, informações ou conclusões prontas ao longo do trabalho, e como isso impactou os resultados?', 2);
  insert into competencies (category_id, name, "order") values ('bloco2', 'Resolução de Problemas', 13) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Identifica as causas reais dos problemas.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Propõe soluções práticas e eficazes.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Direciona esforços para resolver problemas de forma objetiva.', 2);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Nos últimos projetos, quando surgiram problemas, como você lidou com eles desde a identificação até a solução e como avalia o efeito disso no trabalho?', 3);
  insert into competencies (category_id, name, "order") values ('bloco2', 'Tomada de Decisão', 14) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Analisa riscos e benefícios antes de agir.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Decide com base no alinhamento estratégico da empresa.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Nos projetos recentes, como você tomou as decisões mais importantes e de que forma elas contribuíram para o avanço das demandas?', 2);
  insert into competencies (category_id, name, "order") values ('bloco3', 'Foco no Cliente', 15) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Prioriza as necessidades e a satisfação do cliente em suas ações.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Antecipa-se aos problemas que podem afetar a experiência do cliente.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Considerando os projetos recentes, como você buscou entender e atender às expectativas do cliente e qual foi o impacto disso no resultado?', 2);
  insert into competencies (category_id, name, "order") values ('bloco3', 'Atenção ao Cliente', 16) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Demonstra cuidado e dedicação no atendimento às demandas dos clientes.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Responde com clareza e agilidade às solicitações dos clientes.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando nas interações recentes, como você conduziu a comunicação e o suporte ao cliente e como avalia a percepção dele sobre o seu trabalho?', 2);
  insert into competencies (category_id, name, "order") values ('bloco3', 'Negociação / Persuasão', 17) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Apresenta argumentos convincentes para defender ideias e soluções.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Busca o equilíbrio entre os interesses da empresa e do cliente.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Nos projetos recentes, em quais situações você precisou negociar prazos ou soluções e como você conduziu esse processo para chegar a um acordo?', 2);
  insert into competencies (category_id, name, "order") values ('bloco4', 'Comunicação', 18) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Expressa suas ideias de forma clara, objetiva e estruturada.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Ouve ativamente e demonstra compreensão sobre o que foi comunicado.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Utiliza canais adequados para cada tipo de mensagem.', 2);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Considerando as interações recentes, como você avalia sua clareza ao passar informações e como garante que o que foi dito foi realmente compreendido?', 3);
  insert into competencies (category_id, name, "order") values ('bloco4', 'Trabalho em Equipe', 19) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Colabora ativamente com os membros da equipe para atingir objetivos comuns.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Adapta-se às diferentes necessidades e estilos de trabalho dos membros da equipe.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Oferece ajuda aos colegas quando percebe a oportunidade.', 2);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Recebe feedbacks com abertura e positividade.', 3);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando nos projetos mais recentes, como foi sua atuação em conjunto com o time e como isso funcionou no andamento do trabalho?', 4);
  insert into competencies (category_id, name, "order") values ('bloco4', 'Relacionamento Interpessoal', 20) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Mantém bons relacionamentos com colegas e liderança.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Demonstra aceitação e respeito pelas diferenças.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Contribui para a construção de um clima organizacional favorável.', 2);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Considerando as interações mais recentes no trabalho, como você se relacionou com colegas, líderes e clientes de diferentes perfis e como avalia o impacto disso no ambiente?', 3);
  insert into competencies (category_id, name, "order") values ('bloco4', 'Cordialidade', 21) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Estabelece relacionamento gentil e cuidadoso com todas as pessoas.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Pratica tolerância ao lidar com diferenças de opinião.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando nas situações recentes do trabalho, como foi sua postura no trato diário com as pessoas e como isso funcionou na prática?', 2);
  insert into competencies (category_id, name, "order") values ('bloco4', 'Empatia', 22) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Ajusta sua comunicação ao contexto emocional da outra pessoa.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Demonstra sensibilidade diante das necessidades e dificuldades dos colegas.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Ouve o outro com atenção genuína.', 2);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Nos projetos e interações mais recentes, como você lidou com as necessidades dos colegas e como isso influenciou as relações?', 3);
  insert into competencies (category_id, name, "order") values ('bloco4', 'Resolução de Conflitos', 23) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Escuta ativamente as perspectivas das pessoas envolvidas em conflitos.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Busca soluções práticas e eficazes para resolver conflitos.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando em conflitos recentes, como você atuou para lidar com essas situações e como avalia os resultados?', 2);
  insert into competencies (category_id, name, "order") values ('bloco4', 'Disponibilidade (Interna)', 24) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Demonstra prontidão para ajudar e oferecer suporte quando necessário.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Responde prontamente às solicitações e pedidos de apoio da equipe.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Considerando as demandas internas mais recentes, como você se mostrou disponível para apoiar a equipe?', 2);
  insert into competencies (category_id, name, "order") values ('bloco5', 'Comprometimento', 25) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Cumpre as atividades, responsabilidades e objetivos do trabalho de forma empenhada.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Entrega tarefas e combinados no prazo respeitando as regras e princípios da organização.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando nas atividades e projetos mais recentes, como você administrou suas responsabilidades, prazos e possíveis imprevistos? Quando ocorreram dificuldades ou erros, como você os comunicou e conduziu a solução?', 2);
  insert into competencies (category_id, name, "order") values ('bloco5', 'Responsabilidade', 26) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Demonstra segurança ao exercer suas funções.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Assume erros e falhas com transparência.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Considerando situações recentes de trabalho, como você lidou com erros, imprevistos ou falhas quando eles aconteceram, e como isso funcionou na prática?', 2);
  insert into competencies (category_id, name, "order") values ('bloco5', 'Comportamento Ético', 27) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Age de acordo com princípios éticos e valores morais.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Adota postura de discrição em relação aos assuntos da empresa.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando nas decisões e situações recentes do trabalho, como você considerou aspectos éticos no dia a dia e como avalia os efeitos dessas escolhas?', 2);
  insert into competencies (category_id, name, "order") values ('bloco5', 'Confiabilidade', 28) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Cumpre o que promete.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Demonstra coerência entre discurso e prática.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Nos projetos mais recentes, como foi a relação entre o que você combinou ou prometeu e o que de fato entregou, e como isso funcionou para o trabalho?', 2);
  insert into competencies (category_id, name, "order") values ('bloco5', 'Transparência', 29) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Compartilha informações relevantes de forma clara e no tempo adequado.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Expõe suas intenções, limites e dificuldades com honestidade.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando nas situações recentes do trabalho, como você compartilhou informações, limites ou dificuldades com as pessoas envolvidas, e como isso impactou o andamento das atividades?', 2);
  insert into competencies (category_id, name, "order") values ('bloco5', 'Sigilo', 30) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Mantém informações confidenciais em absoluto sigilo.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Age com discrição em assuntos sensíveis.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Considerando situações recentes que envolveram informações sensíveis ou assuntos delicados, como você lidou com essas informações e como avalia os resultados dessa postura?', 2);
  insert into competencies (category_id, name, "order") values ('bloco6', 'Aprendizado Contínuo', 31) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Busca aprendizado contínuo para aprimorar sua atuação.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Demonstra interesse em desenvolver novas habilidades.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando nas experiências de trabalho mais recentes, como você buscou aprender coisas novas e como avalia os efeitos disso?', 2);
  insert into competencies (category_id, name, "order") values ('bloco6', 'Adaptação às Mudanças', 32) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Adapta-se a mudanças com flexibilidade.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Mantém desempenho mesmo diante de cenários novos ou incertos.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Considerando mudanças recentes no trabalho, como você lidou com essas situações e como isso funcionou para dar continuidade às atividades?', 2);
  insert into competencies (category_id, name, "order") values ('bloco6', 'Abertura ao Feedback', 33) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Utiliza feedbacks como oportunidade de desenvolvimento.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Solicita feedbacks para aprimorar sua atuação.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando em situações recentes, como você lidou com feedbacks recebidos e como isso contribuiu para seu desenvolvimento?', 2);
  insert into competencies (category_id, name, "order") values ('bloco6', 'Autodesenvolvimento', 34) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Reflete sobre sua própria atuação.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Busca evolução pessoal e profissional.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Considerando seu trabalho recente, como você refletiu sobre seu próprio desempenho e como isso ajudou a orientar melhorias?', 2);
  insert into competencies (category_id, name, "order") values ('bloco6', 'Visão de Futuro', 35) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Planeja seu desenvolvimento profissional a médio e longo prazo.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Alinha expectativas pessoais aos objetivos da organização.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Pensando no momento atual da sua carreira, como você tem refletido sobre seus próximos passos profissionais?', 2);
  insert into competencies (category_id, name, "order") values ('bloco6', 'Proatividade no Desenvolvimento', 36) returning id into comp_id;
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Busca oportunidades de crescimento dentro da organização.', 0);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'statement', 'Age de forma ativa para evoluir profissionalmente.', 1);
  insert into competency_questions (competency_id, type, text, "order") values (comp_id, 'dialogic', 'Considerando as oportunidades recentes no trabalho, como você tomou iniciativas para se desenvolver profissionalmente?', 2);
end $$;
