-- ============================================================================
-- Seed: tenant "Luis Tortola" (Obra Viva) — organização, cargos, atividades,
-- vínculos de competências e membros, a partir do export do cliente
-- (obravivaequipecargoscompetenciasavaliacoes 2026-08-13).
--
-- Pré-requisito: 0002_seed_competency_library.sql já aplicada — este arquivo
-- NÃO reinsere categorias/competências/perguntas (biblioteca global), apenas
-- confere a cobertura das 36 competências / 127 perguntas do export contra
-- ela (bloco de verificação abaixo) e então referencia os ids reais via
-- correspondência por (nome da competência, ordem da pergunta) — a
-- biblioteca usa uuids gerados em tempo de seed, então não há ids estáveis
-- compartilhados com o export do cliente (que usa ids tipo "q-b1-agilidade-1").
-- ============================================================================

do $$
declare
  v_org_id uuid;
  v_role_id uuid;
  v_missing int;
begin
  -- ---------------------------------------------------------------------
  -- Sanity check: the 36 competencies / 127 questions from the client
  -- export must already exist in the global library (0002). This block
  -- raises instead of silently seeding a partial/duplicate tenant.
  -- ---------------------------------------------------------------------
  select count(*) into v_missing from (
    values

      ('Agilidade', 'bloco1'),
      ('Capacidade de Execução', 'bloco1'),
      ('Organização', 'bloco1'),
      ('Planejamento', 'bloco1'),
      ('Priorização', 'bloco1'),
      ('Orientação para Resultado', 'bloco1'),
      ('Atenção Concentrada', 'bloco1'),
      ('Detalhista', 'bloco1'),
      ('Raciocínio Lógico', 'bloco2'),
      ('Raciocínio Abstrato', 'bloco2'),
      ('Capacidade Investigativa', 'bloco2'),
      ('Senso Crítico', 'bloco2'),
      ('Resolução de Problemas', 'bloco2'),
      ('Tomada de Decisão', 'bloco2'),
      ('Foco no Cliente', 'bloco3'),
      ('Atenção ao Cliente', 'bloco3'),
      ('Negociação / Persuasão', 'bloco3'),
      ('Comunicação', 'bloco4'),
      ('Trabalho em Equipe', 'bloco4'),
      ('Relacionamento Interpessoal', 'bloco4'),
      ('Cordialidade', 'bloco4'),
      ('Empatia', 'bloco4'),
      ('Resolução de Conflitos', 'bloco4'),
      ('Disponibilidade (Interna)', 'bloco4'),
      ('Comprometimento', 'bloco5'),
      ('Responsabilidade', 'bloco5'),
      ('Comportamento Ético', 'bloco5'),
      ('Confiabilidade', 'bloco5'),
      ('Transparência', 'bloco5'),
      ('Sigilo', 'bloco5'),
      ('Aprendizado Contínuo', 'bloco6'),
      ('Adaptação às Mudanças', 'bloco6'),
      ('Abertura ao Feedback', 'bloco6'),
      ('Autodesenvolvimento', 'bloco6'),
      ('Visão de Futuro', 'bloco6'),
      ('Proatividade no Desenvolvimento', 'bloco6')

  ) as expected(name, category_id)
  where not exists (
    select 1 from competencies c where c.name = expected.name and c.category_id = expected.category_id
  );
  if v_missing > 0 then
    raise exception 'Biblioteca global de competências incompleta: % competência(s) do export da Luis Tortola não encontrada(s). Rode 0002_seed_competency_library.sql antes desta migração.', v_missing;
  end if;

  select count(*) into v_missing from (
    values

      ('Agilidade', 0),
      ('Agilidade', 1),
      ('Agilidade', 2),
      ('Agilidade', 3),
      ('Agilidade', 4),
      ('Capacidade de Execução', 0),
      ('Capacidade de Execução', 1),
      ('Capacidade de Execução', 2),
      ('Capacidade de Execução', 3),
      ('Organização', 0),
      ('Organização', 1),
      ('Organização', 2),
      ('Organização', 3),
      ('Organização', 4),
      ('Planejamento', 0),
      ('Planejamento', 1),
      ('Planejamento', 2),
      ('Planejamento', 3),
      ('Planejamento', 4),
      ('Priorização', 0),
      ('Priorização', 1),
      ('Priorização', 2),
      ('Orientação para Resultado', 0),
      ('Orientação para Resultado', 1),
      ('Orientação para Resultado', 2),
      ('Orientação para Resultado', 3),
      ('Orientação para Resultado', 4),
      ('Orientação para Resultado', 5),
      ('Atenção Concentrada', 0),
      ('Atenção Concentrada', 1),
      ('Atenção Concentrada', 2),
      ('Atenção Concentrada', 3),
      ('Detalhista', 0),
      ('Detalhista', 1),
      ('Detalhista', 2),
      ('Raciocínio Lógico', 0),
      ('Raciocínio Lógico', 1),
      ('Raciocínio Lógico', 2),
      ('Raciocínio Lógico', 3),
      ('Raciocínio Abstrato', 0),
      ('Raciocínio Abstrato', 1),
      ('Raciocínio Abstrato', 2),
      ('Capacidade Investigativa', 0),
      ('Capacidade Investigativa', 1),
      ('Capacidade Investigativa', 2),
      ('Capacidade Investigativa', 3),
      ('Senso Crítico', 0),
      ('Senso Crítico', 1),
      ('Senso Crítico', 2),
      ('Resolução de Problemas', 0),
      ('Resolução de Problemas', 1),
      ('Resolução de Problemas', 2),
      ('Resolução de Problemas', 3),
      ('Tomada de Decisão', 0),
      ('Tomada de Decisão', 1),
      ('Tomada de Decisão', 2),
      ('Foco no Cliente', 0),
      ('Foco no Cliente', 1),
      ('Foco no Cliente', 2),
      ('Atenção ao Cliente', 0),
      ('Atenção ao Cliente', 1),
      ('Atenção ao Cliente', 2),
      ('Negociação / Persuasão', 0),
      ('Negociação / Persuasão', 1),
      ('Negociação / Persuasão', 2),
      ('Comunicação', 0),
      ('Comunicação', 1),
      ('Comunicação', 2),
      ('Comunicação', 3),
      ('Trabalho em Equipe', 0),
      ('Trabalho em Equipe', 1),
      ('Trabalho em Equipe', 2),
      ('Trabalho em Equipe', 3),
      ('Trabalho em Equipe', 4),
      ('Relacionamento Interpessoal', 0),
      ('Relacionamento Interpessoal', 1),
      ('Relacionamento Interpessoal', 2),
      ('Relacionamento Interpessoal', 3),
      ('Cordialidade', 0),
      ('Cordialidade', 1),
      ('Cordialidade', 2),
      ('Empatia', 0),
      ('Empatia', 1),
      ('Empatia', 2),
      ('Empatia', 3),
      ('Resolução de Conflitos', 0),
      ('Resolução de Conflitos', 1),
      ('Resolução de Conflitos', 2),
      ('Disponibilidade (Interna)', 0),
      ('Disponibilidade (Interna)', 1),
      ('Disponibilidade (Interna)', 2),
      ('Comprometimento', 0),
      ('Comprometimento', 1),
      ('Comprometimento', 2),
      ('Responsabilidade', 0),
      ('Responsabilidade', 1),
      ('Responsabilidade', 2),
      ('Comportamento Ético', 0),
      ('Comportamento Ético', 1),
      ('Comportamento Ético', 2),
      ('Confiabilidade', 0),
      ('Confiabilidade', 1),
      ('Confiabilidade', 2),
      ('Transparência', 0),
      ('Transparência', 1),
      ('Transparência', 2),
      ('Sigilo', 0),
      ('Sigilo', 1),
      ('Sigilo', 2),
      ('Aprendizado Contínuo', 0),
      ('Aprendizado Contínuo', 1),
      ('Aprendizado Contínuo', 2),
      ('Adaptação às Mudanças', 0),
      ('Adaptação às Mudanças', 1),
      ('Adaptação às Mudanças', 2),
      ('Abertura ao Feedback', 0),
      ('Abertura ao Feedback', 1),
      ('Abertura ao Feedback', 2),
      ('Autodesenvolvimento', 0),
      ('Autodesenvolvimento', 1),
      ('Autodesenvolvimento', 2),
      ('Visão de Futuro', 0),
      ('Visão de Futuro', 1),
      ('Visão de Futuro', 2),
      ('Proatividade no Desenvolvimento', 0),
      ('Proatividade no Desenvolvimento', 1),
      ('Proatividade no Desenvolvimento', 2)

  ) as expected(comp_name, q_order)
  where not exists (
    select 1
    from competency_questions cq
    join competencies c on c.id = cq.competency_id
    where c.name = expected.comp_name and cq."order" = expected.q_order
  );
  if v_missing > 0 then
    raise exception 'Biblioteca global de perguntas incompleta: % pergunta(s) do export da Luis Tortola não encontrada(s) por (competência, ordem). Rode 0002_seed_competency_library.sql antes desta migração.', v_missing;
  end if;

  -- ---------------------------------------------------------------------
  -- Organization
  -- ---------------------------------------------------------------------
  insert into organizations (slug, name, design_tokens, enabled_evaluation_types, role_types)
  values (
    'luis-tortola',
    'Luis Tortola',
    '{
      "colorPrimary": "#0f172a",
      "colorSecondary": "#334155",
      "colorSuccess": "#15803d",
      "colorWarning": "#b45309",
      "colorDanger": "#ef4444",
      "colorSurface": "#ffffff",
      "colorSurfaceMuted": "#f8fafc",
      "colorTextPrimary": "#0f172a",
      "colorTextMuted": "#64748b",
      "fontFamily": "Inter, system-ui, sans-serif",
      "radiusBase": "16px",
      "density": "comfortable",
      "logoUrlLight": "/orgs/luis-tortola/logo.png",
      "logoUrlDark": "/orgs/luis-tortola/logo.png",
      "faviconUrl": "/orgs/luis-tortola/logo.png",
      "backgroundImageUrl": "/orgs/luis-tortola/hero-background.png",
      "footerLogoUrl": "/orgs/luis-tortola/nossa-logo.png",
      "footerIconUrl": "/orgs/luis-tortola/nossa-icon.png",
      "footerText": "Ferramenta de Avaliação de Desempenho",
      "footerSubtext": "desenvolvido por NOSSA Pessoas & Empresas"
    }'::jsonb,
    array['dialogica','tradicional','atividades'],
    array['leadership','collaborator']
  )
  returning id into v_org_id;

  -- ---------------------------------------------------------------------
  -- Mapping tables (dropped at commit): json role id -> real role uuid,
  -- and json question id -> real (competency_id, question_id) via the
  -- (competency name, question order) match validated above.
  -- ---------------------------------------------------------------------
  create temporary table tmp_roles (json_id text primary key, role_id uuid not null, name text not null) on commit drop;

  create temporary table tmp_json_questions (json_qid text primary key, comp_name text not null, q_order int not null) on commit drop;
  insert into tmp_json_questions (json_qid, comp_name, q_order) values

    ('q-b1-agilidade-1', 'Agilidade', 0),
    ('q-b1-agilidade-2', 'Agilidade', 1),
    ('q-b1-agilidade-3', 'Agilidade', 2),
    ('q-b1-agilidade-4', 'Agilidade', 3),
    ('q-b1-agilidade-dial', 'Agilidade', 4),
    ('q-b1-exec-1', 'Capacidade de Execução', 0),
    ('q-b1-exec-2', 'Capacidade de Execução', 1),
    ('q-b1-exec-3', 'Capacidade de Execução', 2),
    ('q-b1-exec-dial', 'Capacidade de Execução', 3),
    ('q-b1-org-1', 'Organização', 0),
    ('q-b1-org-2', 'Organização', 1),
    ('q-b1-org-3', 'Organização', 2),
    ('q-b1-org-4', 'Organização', 3),
    ('q-b1-org-dial', 'Organização', 4),
    ('q-b1-plan-1', 'Planejamento', 0),
    ('q-b1-plan-2', 'Planejamento', 1),
    ('q-b1-plan-3', 'Planejamento', 2),
    ('q-b1-plan-4', 'Planejamento', 3),
    ('q-b1-plan-dial', 'Planejamento', 4),
    ('q-b1-prior-1', 'Priorização', 0),
    ('q-b1-prior-2', 'Priorização', 1),
    ('q-b1-prior-dial', 'Priorização', 2),
    ('q-b1-result-1', 'Orientação para Resultado', 0),
    ('q-b1-result-2', 'Orientação para Resultado', 1),
    ('q-b1-result-3', 'Orientação para Resultado', 2),
    ('q-b1-result-4', 'Orientação para Resultado', 3),
    ('q-b1-result-5', 'Orientação para Resultado', 4),
    ('q-b1-result-dial', 'Orientação para Resultado', 5),
    ('q-b1-atenc-1', 'Atenção Concentrada', 0),
    ('q-b1-atenc-2', 'Atenção Concentrada', 1),
    ('q-b1-atenc-3', 'Atenção Concentrada', 2),
    ('q-b1-atenc-dial', 'Atenção Concentrada', 3),
    ('q-b1-detal-1', 'Detalhista', 0),
    ('q-b1-detal-2', 'Detalhista', 1),
    ('q-b1-detal-dial', 'Detalhista', 2),
    ('q-b2-rl-1', 'Raciocínio Lógico', 0),
    ('q-b2-rl-2', 'Raciocínio Lógico', 1),
    ('q-b2-rl-3', 'Raciocínio Lógico', 2),
    ('q-b2-rl-dial', 'Raciocínio Lógico', 3),
    ('q-b2-ra-1', 'Raciocínio Abstrato', 0),
    ('q-b2-ra-2', 'Raciocínio Abstrato', 1),
    ('q-b2-ra-dial', 'Raciocínio Abstrato', 2),
    ('q-b2-ci-1', 'Capacidade Investigativa', 0),
    ('q-b2-ci-2', 'Capacidade Investigativa', 1),
    ('q-b2-ci-3', 'Capacidade Investigativa', 2),
    ('q-b2-ci-dial', 'Capacidade Investigativa', 3),
    ('q-b2-sc-1', 'Senso Crítico', 0),
    ('q-b2-sc-2', 'Senso Crítico', 1),
    ('q-b2-sc-dial', 'Senso Crítico', 2),
    ('q-b2-rp-1', 'Resolução de Problemas', 0),
    ('q-b2-rp-2', 'Resolução de Problemas', 1),
    ('q-b2-rp-3', 'Resolução de Problemas', 2),
    ('q-b2-rp-dial', 'Resolução de Problemas', 3),
    ('q-b2-td-1', 'Tomada de Decisão', 0),
    ('q-b2-td-2', 'Tomada de Decisão', 1),
    ('q-b2-td-dial', 'Tomada de Decisão', 2),
    ('q-b3-fc-1', 'Foco no Cliente', 0),
    ('q-b3-fc-2', 'Foco no Cliente', 1),
    ('q-b3-fc-dial', 'Foco no Cliente', 2),
    ('q-b3-ac-1', 'Atenção ao Cliente', 0),
    ('q-b3-ac-2', 'Atenção ao Cliente', 1),
    ('q-b3-ac-dial', 'Atenção ao Cliente', 2),
    ('q-b3-np-1', 'Negociação / Persuasão', 0),
    ('q-b3-np-2', 'Negociação / Persuasão', 1),
    ('q-b3-np-dial', 'Negociação / Persuasão', 2),
    ('q-b4-com-1', 'Comunicação', 0),
    ('q-b4-com-2', 'Comunicação', 1),
    ('q-b4-com-3', 'Comunicação', 2),
    ('q-b4-com-dial', 'Comunicação', 3),
    ('q-b4-te-1', 'Trabalho em Equipe', 0),
    ('q-b4-te-2', 'Trabalho em Equipe', 1),
    ('q-b4-te-3', 'Trabalho em Equipe', 2),
    ('q-b4-te-4', 'Trabalho em Equipe', 3),
    ('q-b4-te-dial', 'Trabalho em Equipe', 4),
    ('q-b4-ri-1', 'Relacionamento Interpessoal', 0),
    ('q-b4-ri-2', 'Relacionamento Interpessoal', 1),
    ('q-b4-ri-3', 'Relacionamento Interpessoal', 2),
    ('q-b4-ri-dial', 'Relacionamento Interpessoal', 3),
    ('q-b4-cor-1', 'Cordialidade', 0),
    ('q-b4-cor-2', 'Cordialidade', 1),
    ('q-b4-cor-dial', 'Cordialidade', 2),
    ('q-b4-emp-1', 'Empatia', 0),
    ('q-b4-emp-2', 'Empatia', 1),
    ('q-b4-emp-3', 'Empatia', 2),
    ('q-b4-emp-dial', 'Empatia', 3),
    ('q-b4-rc-1', 'Resolução de Conflitos', 0),
    ('q-b4-rc-2', 'Resolução de Conflitos', 1),
    ('q-b4-rc-dial', 'Resolução de Conflitos', 2),
    ('q-b4-di-1', 'Disponibilidade (Interna)', 0),
    ('q-b4-di-2', 'Disponibilidade (Interna)', 1),
    ('q-b4-di-dial', 'Disponibilidade (Interna)', 2),
    ('q-b5-comp-1', 'Comprometimento', 0),
    ('q-b5-comp-2', 'Comprometimento', 1),
    ('q-b5-comp-dial', 'Comprometimento', 2),
    ('q-b5-resp-1', 'Responsabilidade', 0),
    ('q-b5-resp-2', 'Responsabilidade', 1),
    ('q-b5-resp-dial', 'Responsabilidade', 2),
    ('q-b5-ce-1', 'Comportamento Ético', 0),
    ('q-b5-ce-2', 'Comportamento Ético', 1),
    ('q-b5-ce-dial', 'Comportamento Ético', 2),
    ('q-b5-conf-1', 'Confiabilidade', 0),
    ('q-b5-conf-2', 'Confiabilidade', 1),
    ('q-b5-conf-dial', 'Confiabilidade', 2),
    ('q-b5-trans-1', 'Transparência', 0),
    ('q-b5-trans-2', 'Transparência', 1),
    ('q-b5-trans-dial', 'Transparência', 2),
    ('q-b5-sig-1', 'Sigilo', 0),
    ('q-b5-sig-2', 'Sigilo', 1),
    ('q-b5-sig-dial', 'Sigilo', 2),
    ('q-b6-ac-1', 'Aprendizado Contínuo', 0),
    ('q-b6-ac-2', 'Aprendizado Contínuo', 1),
    ('q-b6-ac-dial', 'Aprendizado Contínuo', 2),
    ('q-b6-am-1', 'Adaptação às Mudanças', 0),
    ('q-b6-am-2', 'Adaptação às Mudanças', 1),
    ('q-b6-am-dial', 'Adaptação às Mudanças', 2),
    ('q-b6-af-1', 'Abertura ao Feedback', 0),
    ('q-b6-af-2', 'Abertura ao Feedback', 1),
    ('q-b6-af-dial', 'Abertura ao Feedback', 2),
    ('q-b6-ad-1', 'Autodesenvolvimento', 0),
    ('q-b6-ad-2', 'Autodesenvolvimento', 1),
    ('q-b6-ad-dial', 'Autodesenvolvimento', 2),
    ('q-b6-vf-1', 'Visão de Futuro', 0),
    ('q-b6-vf-2', 'Visão de Futuro', 1),
    ('q-b6-vf-dial', 'Visão de Futuro', 2),
    ('q-b6-pd-1', 'Proatividade no Desenvolvimento', 0),
    ('q-b6-pd-2', 'Proatividade no Desenvolvimento', 1),
    ('q-b6-pd-dial', 'Proatividade no Desenvolvimento', 2);


  create temporary table tmp_qmap (json_qid text primary key, competency_id uuid not null, question_id uuid not null) on commit drop;
  insert into tmp_qmap (json_qid, competency_id, question_id)
  select jq.json_qid, cq.competency_id, cq.id
  from tmp_json_questions jq
  join competencies c on c.name = jq.comp_name
  join competency_questions cq on cq.competency_id = c.id and cq."order" = jq.q_order;

  create temporary table tmp_role_questions (role_json_id text not null, json_qid text not null) on commit drop;

  insert into tmp_role_questions (role_json_id, json_qid) values
    ('default-role-3d-manager', 'q-b6-ad-1'),
    ('default-role-3d-manager', 'q-b6-ad-2'),
    ('default-role-3d-manager', 'q-b6-ad-dial'),
    ('default-role-3d-manager', 'q-b1-exec-1'),
    ('default-role-3d-manager', 'q-b1-exec-2'),
    ('default-role-3d-manager', 'q-b1-exec-3'),
    ('default-role-3d-manager', 'q-b1-exec-dial'),
    ('default-role-3d-manager', 'q-b2-ci-1'),
    ('default-role-3d-manager', 'q-b2-ci-2'),
    ('default-role-3d-manager', 'q-b2-ci-3'),
    ('default-role-3d-manager', 'q-b2-ci-dial'),
    ('default-role-3d-manager', 'q-b4-com-1'),
    ('default-role-3d-manager', 'q-b4-com-2'),
    ('default-role-3d-manager', 'q-b4-com-3'),
    ('default-role-3d-manager', 'q-b4-com-dial'),
    ('default-role-3d-manager', 'q-b1-detal-1'),
    ('default-role-3d-manager', 'q-b1-detal-2'),
    ('default-role-3d-manager', 'q-b1-detal-dial'),
    ('default-role-3d-manager', 'q-b1-org-1'),
    ('default-role-3d-manager', 'q-b1-org-2'),
    ('default-role-3d-manager', 'q-b1-org-3'),
    ('default-role-3d-manager', 'q-b1-org-4'),
    ('default-role-3d-manager', 'q-b1-org-dial'),
    ('default-role-3d-manager', 'q-b1-result-1'),
    ('default-role-3d-manager', 'q-b1-result-2'),
    ('default-role-3d-manager', 'q-b1-result-3'),
    ('default-role-3d-manager', 'q-b1-result-4'),
    ('default-role-3d-manager', 'q-b1-result-5'),
    ('default-role-3d-manager', 'q-b1-result-dial'),
    ('default-role-3d-manager', 'q-b1-plan-1'),
    ('default-role-3d-manager', 'q-b1-plan-2'),
    ('default-role-3d-manager', 'q-b1-plan-3'),
    ('default-role-3d-manager', 'q-b1-plan-4'),
    ('default-role-3d-manager', 'q-b1-plan-dial'),
    ('default-role-3d-manager', 'q-b4-ri-1'),
    ('default-role-3d-manager', 'q-b4-ri-2'),
    ('default-role-3d-manager', 'q-b4-ri-3'),
    ('default-role-3d-manager', 'q-b4-ri-dial'),
    ('default-role-administrador', 'q-b1-atenc-1'),
    ('default-role-administrador', 'q-b1-atenc-2'),
    ('default-role-administrador', 'q-b1-atenc-3'),
    ('default-role-administrador', 'q-b1-atenc-dial'),
    ('default-role-administrador', 'q-b1-exec-1'),
    ('default-role-administrador', 'q-b1-exec-2'),
    ('default-role-administrador', 'q-b1-exec-3'),
    ('default-role-administrador', 'q-b1-exec-dial'),
    ('default-role-administrador', 'q-b4-com-1'),
    ('default-role-administrador', 'q-b4-com-2'),
    ('default-role-administrador', 'q-b4-com-3'),
    ('default-role-administrador', 'q-b4-com-dial'),
    ('default-role-administrador', 'q-b5-comp-1'),
    ('default-role-administrador', 'q-b5-comp-2'),
    ('default-role-administrador', 'q-b5-comp-dial'),
    ('default-role-administrador', 'q-b1-org-1'),
    ('default-role-administrador', 'q-b1-org-2'),
    ('default-role-administrador', 'q-b1-org-3'),
    ('default-role-administrador', 'q-b1-org-4'),
    ('default-role-administrador', 'q-b1-org-dial'),
    ('default-role-administrador', 'q-b1-plan-1'),
    ('default-role-administrador', 'q-b1-plan-2'),
    ('default-role-administrador', 'q-b1-plan-3'),
    ('default-role-administrador', 'q-b1-plan-4'),
    ('default-role-administrador', 'q-b1-plan-dial'),
    ('default-role-administrador', 'q-b4-ri-1'),
    ('default-role-administrador', 'q-b4-ri-2'),
    ('default-role-administrador', 'q-b4-ri-3'),
    ('default-role-administrador', 'q-b4-ri-dial'),
    ('default-role-administrador', 'q-b2-rp-1'),
    ('default-role-administrador', 'q-b2-rp-2'),
    ('default-role-administrador', 'q-b2-rp-3'),
    ('default-role-administrador', 'q-b2-rp-dial'),
    ('default-role-administrador', 'q-b2-td-1'),
    ('default-role-administrador', 'q-b2-td-2'),
    ('default-role-administrador', 'q-b2-td-dial'),
    ('default-role-desenvolvedor-projetos', 'q-b1-atenc-1'),
    ('default-role-desenvolvedor-projetos', 'q-b1-atenc-2'),
    ('default-role-desenvolvedor-projetos', 'q-b1-atenc-3'),
    ('default-role-desenvolvedor-projetos', 'q-b1-atenc-dial'),
    ('default-role-desenvolvedor-projetos', 'q-b6-ad-1'),
    ('default-role-desenvolvedor-projetos', 'q-b6-ad-2'),
    ('default-role-desenvolvedor-projetos', 'q-b6-ad-dial'),
    ('default-role-desenvolvedor-projetos', 'q-b1-exec-1'),
    ('default-role-desenvolvedor-projetos', 'q-b1-exec-2'),
    ('default-role-desenvolvedor-projetos', 'q-b1-exec-3'),
    ('default-role-desenvolvedor-projetos', 'q-b1-exec-dial'),
    ('default-role-desenvolvedor-projetos', 'q-b4-com-1'),
    ('default-role-desenvolvedor-projetos', 'q-b4-com-2'),
    ('default-role-desenvolvedor-projetos', 'q-b4-com-3'),
    ('default-role-desenvolvedor-projetos', 'q-b4-com-dial'),
    ('default-role-desenvolvedor-projetos', 'q-b1-org-1'),
    ('default-role-desenvolvedor-projetos', 'q-b1-org-2'),
    ('default-role-desenvolvedor-projetos', 'q-b1-org-3'),
    ('default-role-desenvolvedor-projetos', 'q-b1-org-4'),
    ('default-role-desenvolvedor-projetos', 'q-b1-org-dial'),
    ('default-role-desenvolvedor-projetos', 'q-b1-plan-1'),
    ('default-role-desenvolvedor-projetos', 'q-b1-plan-2'),
    ('default-role-desenvolvedor-projetos', 'q-b1-plan-3'),
    ('default-role-desenvolvedor-projetos', 'q-b1-plan-4'),
    ('default-role-desenvolvedor-projetos', 'q-b1-plan-dial'),
    ('default-role-desenvolvedor-projetos', 'q-b2-ra-1'),
    ('default-role-desenvolvedor-projetos', 'q-b2-ra-2'),
    ('default-role-desenvolvedor-projetos', 'q-b2-ra-dial'),
    ('default-role-desenvolvedor-projetos', 'q-b2-rl-1'),
    ('default-role-desenvolvedor-projetos', 'q-b2-rl-2'),
    ('default-role-desenvolvedor-projetos', 'q-b2-rl-3'),
    ('default-role-desenvolvedor-projetos', 'q-b2-rl-dial'),
    ('default-role-desenvolvedor-projetos', 'q-b2-rp-1'),
    ('default-role-desenvolvedor-projetos', 'q-b2-rp-2'),
    ('default-role-desenvolvedor-projetos', 'q-b2-rp-3'),
    ('default-role-desenvolvedor-projetos', 'q-b2-rp-dial'),
    ('default-role-desenvolvedor-projetos', 'q-b4-te-1'),
    ('default-role-desenvolvedor-projetos', 'q-b4-te-2'),
    ('default-role-desenvolvedor-projetos', 'q-b4-te-3'),
    ('default-role-desenvolvedor-projetos', 'q-b4-te-4'),
    ('default-role-desenvolvedor-projetos', 'q-b4-te-dial'),
    ('default-role-desenvolvedor-projetos', 'q-b2-td-1'),
    ('default-role-desenvolvedor-projetos', 'q-b2-td-2'),
    ('default-role-desenvolvedor-projetos', 'q-b2-td-dial'),
    ('default-role-financeiro', 'q-b1-atenc-1'),
    ('default-role-financeiro', 'q-b1-atenc-2'),
    ('default-role-financeiro', 'q-b1-atenc-3'),
    ('default-role-financeiro', 'q-b1-atenc-dial'),
    ('default-role-financeiro', 'q-b5-ce-1'),
    ('default-role-financeiro', 'q-b5-ce-2'),
    ('default-role-financeiro', 'q-b5-ce-dial'),
    ('default-role-financeiro', 'q-b4-com-1'),
    ('default-role-financeiro', 'q-b4-com-2'),
    ('default-role-financeiro', 'q-b4-com-3'),
    ('default-role-financeiro', 'q-b4-com-dial'),
    ('default-role-financeiro', 'q-b5-conf-1'),
    ('default-role-financeiro', 'q-b5-conf-2'),
    ('default-role-financeiro', 'q-b5-conf-dial'),
    ('default-role-financeiro', 'q-b5-comp-1'),
    ('default-role-financeiro', 'q-b5-comp-2'),
    ('default-role-financeiro', 'q-b5-comp-dial'),
    ('default-role-financeiro', 'q-b3-np-1'),
    ('default-role-financeiro', 'q-b3-np-2'),
    ('default-role-financeiro', 'q-b3-np-dial'),
    ('default-role-financeiro', 'q-b1-org-1'),
    ('default-role-financeiro', 'q-b1-org-2'),
    ('default-role-financeiro', 'q-b1-org-3'),
    ('default-role-financeiro', 'q-b1-org-4'),
    ('default-role-financeiro', 'q-b1-org-dial'),
    ('default-role-financeiro', 'q-b1-plan-1'),
    ('default-role-financeiro', 'q-b1-plan-2'),
    ('default-role-financeiro', 'q-b1-plan-3'),
    ('default-role-financeiro', 'q-b1-plan-4'),
    ('default-role-financeiro', 'q-b1-plan-dial'),
    ('default-role-financeiro', 'q-b4-ri-1'),
    ('default-role-financeiro', 'q-b4-ri-2'),
    ('default-role-financeiro', 'q-b4-ri-3'),
    ('default-role-financeiro', 'q-b4-ri-dial'),
    ('default-role-financeiro', 'q-b2-rp-1'),
    ('default-role-financeiro', 'q-b2-rp-2'),
    ('default-role-financeiro', 'q-b2-rp-3'),
    ('default-role-financeiro', 'q-b2-rp-dial'),
    ('default-role-financeiro', 'q-b5-sig-1'),
    ('default-role-financeiro', 'q-b5-sig-2'),
    ('default-role-financeiro', 'q-b5-sig-dial'),
    ('default-role-financeiro', 'q-b2-td-1'),
    ('default-role-financeiro', 'q-b2-td-2'),
    ('default-role-financeiro', 'q-b2-td-dial'),
    ('default-role-gestor-obra', 'q-b1-atenc-1'),
    ('default-role-gestor-obra', 'q-b1-atenc-2'),
    ('default-role-gestor-obra', 'q-b1-atenc-3'),
    ('default-role-gestor-obra', 'q-b1-atenc-dial'),
    ('default-role-gestor-obra', 'q-b6-ad-1'),
    ('default-role-gestor-obra', 'q-b6-ad-2'),
    ('default-role-gestor-obra', 'q-b6-ad-dial'),
    ('default-role-gestor-obra', 'q-b1-exec-1'),
    ('default-role-gestor-obra', 'q-b1-exec-2'),
    ('default-role-gestor-obra', 'q-b1-exec-3'),
    ('default-role-gestor-obra', 'q-b1-exec-dial'),
    ('default-role-gestor-obra', 'q-b3-np-1'),
    ('default-role-gestor-obra', 'q-b3-np-2'),
    ('default-role-gestor-obra', 'q-b3-np-dial'),
    ('default-role-gestor-obra', 'q-b1-org-1'),
    ('default-role-gestor-obra', 'q-b1-org-2'),
    ('default-role-gestor-obra', 'q-b1-org-3'),
    ('default-role-gestor-obra', 'q-b1-org-4'),
    ('default-role-gestor-obra', 'q-b1-org-dial'),
    ('default-role-gestor-obra', 'q-b4-ri-1'),
    ('default-role-gestor-obra', 'q-b4-ri-2'),
    ('default-role-gestor-obra', 'q-b4-ri-3'),
    ('default-role-gestor-obra', 'q-b4-ri-dial'),
    ('default-role-gestor-obra', 'q-b2-rp-1'),
    ('default-role-gestor-obra', 'q-b2-rp-2'),
    ('default-role-gestor-obra', 'q-b2-rp-3'),
    ('default-role-gestor-obra', 'q-b2-rp-dial'),
    ('default-role-gestor-obra', 'q-b2-sc-1'),
    ('default-role-gestor-obra', 'q-b2-sc-2'),
    ('default-role-gestor-obra', 'q-b2-sc-dial'),
    ('default-role-gestor-obra', 'q-b2-td-1'),
    ('default-role-gestor-obra', 'q-b2-td-2'),
    ('default-role-gestor-obra', 'q-b2-td-dial'),
    ('default-role-gerente-comercial', 'q-b3-ac-1'),
    ('default-role-gerente-comercial', 'q-b3-ac-2'),
    ('default-role-gerente-comercial', 'q-b3-ac-dial'),
    ('default-role-gerente-comercial', 'q-b6-ad-1'),
    ('default-role-gerente-comercial', 'q-b6-ad-2'),
    ('default-role-gerente-comercial', 'q-b6-ad-dial'),
    ('default-role-gerente-comercial', 'q-b4-cor-1'),
    ('default-role-gerente-comercial', 'q-b4-cor-2'),
    ('default-role-gerente-comercial', 'q-b4-cor-dial'),
    ('default-role-gerente-comercial', 'q-b5-comp-1'),
    ('default-role-gerente-comercial', 'q-b5-comp-2'),
    ('default-role-gerente-comercial', 'q-b5-comp-dial'),
    ('default-role-gerente-comercial', 'q-b1-org-1'),
    ('default-role-gerente-comercial', 'q-b1-org-2'),
    ('default-role-gerente-comercial', 'q-b1-org-3'),
    ('default-role-gerente-comercial', 'q-b1-org-4'),
    ('default-role-gerente-comercial', 'q-b1-org-dial'),
    ('default-role-gerente-comercial', 'q-b1-plan-1'),
    ('default-role-gerente-comercial', 'q-b1-plan-2'),
    ('default-role-gerente-comercial', 'q-b1-plan-3'),
    ('default-role-gerente-comercial', 'q-b1-plan-4'),
    ('default-role-gerente-comercial', 'q-b1-plan-dial'),
    ('default-role-gerente-comercial', 'q-b4-ri-1'),
    ('default-role-gerente-comercial', 'q-b4-ri-2'),
    ('default-role-gerente-comercial', 'q-b4-ri-3'),
    ('default-role-gerente-comercial', 'q-b4-ri-dial'),
    ('default-role-gerente-comercial', 'q-b5-resp-1'),
    ('default-role-gerente-comercial', 'q-b5-resp-2'),
    ('default-role-gerente-comercial', 'q-b5-resp-dial'),
    ('default-role-gerente-comercial', 'q-b2-rp-1'),
    ('default-role-gerente-comercial', 'q-b2-rp-2'),
    ('default-role-gerente-comercial', 'q-b2-rp-3'),
    ('default-role-gerente-comercial', 'q-b2-rp-dial'),
    ('default-role-gerente-comercial', 'q-b2-td-1'),
    ('default-role-gerente-comercial', 'q-b2-td-2'),
    ('default-role-gerente-comercial', 'q-b2-td-dial'),
    ('default-role-coordenadora-projetos', 'q-b6-ad-1'),
    ('default-role-coordenadora-projetos', 'q-b6-ad-2'),
    ('default-role-coordenadora-projetos', 'q-b6-ad-dial'),
    ('default-role-coordenadora-projetos', 'q-b2-ci-1'),
    ('default-role-coordenadora-projetos', 'q-b2-ci-2'),
    ('default-role-coordenadora-projetos', 'q-b2-ci-3'),
    ('default-role-coordenadora-projetos', 'q-b2-ci-dial'),
    ('default-role-coordenadora-projetos', 'q-b1-detal-1'),
    ('default-role-coordenadora-projetos', 'q-b1-detal-2'),
    ('default-role-coordenadora-projetos', 'q-b1-detal-dial'),
    ('default-role-coordenadora-projetos', 'q-b3-fc-1'),
    ('default-role-coordenadora-projetos', 'q-b3-fc-2'),
    ('default-role-coordenadora-projetos', 'q-b3-fc-dial'),
    ('default-role-coordenadora-projetos', 'q-b1-org-1'),
    ('default-role-coordenadora-projetos', 'q-b1-org-2'),
    ('default-role-coordenadora-projetos', 'q-b1-org-3'),
    ('default-role-coordenadora-projetos', 'q-b1-org-4'),
    ('default-role-coordenadora-projetos', 'q-b1-org-dial'),
    ('default-role-coordenadora-projetos', 'q-b2-rp-2'),
    ('default-role-coordenadora-projetos', 'q-b2-rp-3'),
    ('default-role-coordenadora-projetos', 'q-b2-rp-dial'),
    ('default-role-coordenadora-projetos', 'q-b2-td-1'),
    ('default-role-coordenadora-projetos', 'q-b2-td-2'),
    ('default-role-coordenadora-projetos', 'q-b2-td-dial'),
    ('default-role-coordenadora-projetos', 'q-b1-agilidade-1'),
    ('default-role-coordenadora-projetos', 'q-b1-agilidade-2'),
    ('default-role-coordenadora-projetos', 'q-b1-agilidade-3'),
    ('default-role-coordenadora-projetos', 'q-b1-agilidade-dial'),
    ('default-role-coordenadora-projetos', 'q-b1-result-1'),
    ('default-role-coordenadora-projetos', 'q-b1-result-2'),
    ('default-role-coordenadora-projetos', 'q-b1-result-3'),
    ('default-role-coordenadora-projetos', 'q-b1-result-4'),
    ('default-role-coordenadora-projetos', 'q-b1-result-5'),
    ('default-role-coordenadora-projetos', 'q-b1-result-dial'),
    ('default-role-coordenadora-projetos', 'q-b2-rl-1'),
    ('default-role-coordenadora-projetos', 'q-b2-rl-2'),
    ('default-role-coordenadora-projetos', 'q-b2-rl-3'),
    ('default-role-coordenadora-projetos', 'q-b2-rl-dial'),
    ('default-role-coordenadora-projetos', 'q-b2-sc-1'),
    ('default-role-coordenadora-projetos', 'q-b2-sc-2'),
    ('default-role-coordenadora-projetos', 'q-b2-sc-dial'),
    ('default-role-coordenadora-projetos', 'q-b3-ac-1'),
    ('default-role-coordenadora-projetos', 'q-b3-ac-2'),
    ('default-role-coordenadora-projetos', 'q-b3-ac-dial'),
    ('default-role-coordenadora-projetos', 'q-b3-np-1'),
    ('default-role-coordenadora-projetos', 'q-b3-np-2'),
    ('default-role-coordenadora-projetos', 'q-b3-np-dial'),
    ('default-role-coordenadora-projetos', 'q-b4-com-1'),
    ('default-role-coordenadora-projetos', 'q-b4-com-2'),
    ('default-role-coordenadora-projetos', 'q-b4-com-3'),
    ('default-role-coordenadora-projetos', 'q-b4-com-dial'),
    ('default-role-coordenadora-projetos', 'q-b4-te-1'),
    ('default-role-coordenadora-projetos', 'q-b4-te-2'),
    ('default-role-coordenadora-projetos', 'q-b4-te-3'),
    ('default-role-coordenadora-projetos', 'q-b4-te-4'),
    ('default-role-coordenadora-projetos', 'q-b4-te-dial'),
    ('default-role-coordenadora-projetos', 'q-b4-ri-1'),
    ('default-role-coordenadora-projetos', 'q-b4-ri-2'),
    ('default-role-coordenadora-projetos', 'q-b4-ri-3'),
    ('default-role-coordenadora-projetos', 'q-b4-ri-dial'),
    ('default-role-coordenadora-projetos', 'q-b4-di-dial'),
    ('default-role-coordenadora-projetos', 'q-b4-di-1'),
    ('default-role-coordenadora-projetos', 'q-b5-ce-1'),
    ('default-role-coordenadora-projetos', 'q-b5-ce-2'),
    ('default-role-coordenadora-projetos', 'q-b5-ce-dial'),
    ('default-role-coordenadora-projetos', 'q-b5-comp-1'),
    ('default-role-coordenadora-projetos', 'q-b5-comp-2'),
    ('default-role-coordenadora-projetos', 'q-b5-comp-dial'),
    ('default-role-coordenadora-projetos', 'q-b6-ac-1'),
    ('default-role-coordenadora-projetos', 'q-b6-ac-2'),
    ('default-role-coordenadora-projetos', 'q-b6-ac-dial'),
    ('default-role-auxiliar-servicos-gerais', 'q-b1-org-1'),
    ('default-role-auxiliar-servicos-gerais', 'q-b1-org-2'),
    ('default-role-auxiliar-servicos-gerais', 'q-b1-org-3'),
    ('default-role-auxiliar-servicos-gerais', 'q-b1-org-4'),
    ('default-role-auxiliar-servicos-gerais', 'q-b1-org-dial'),
    ('default-role-auxiliar-servicos-gerais', 'q-b5-comp-1'),
    ('default-role-auxiliar-servicos-gerais', 'q-b5-comp-2'),
    ('default-role-auxiliar-servicos-gerais', 'q-b5-comp-dial'),
    ('default-role-auxiliar-servicos-gerais', 'q-b4-ri-1'),
    ('default-role-auxiliar-servicos-gerais', 'q-b4-ri-2'),
    ('default-role-auxiliar-servicos-gerais', 'q-b4-ri-3'),
    ('default-role-auxiliar-servicos-gerais', 'q-b4-ri-dial'),
    ('default-role-auxiliar-servicos-gerais', 'q-b5-resp-1'),
    ('default-role-auxiliar-servicos-gerais', 'q-b5-resp-2'),
    ('default-role-auxiliar-servicos-gerais', 'q-b5-resp-dial'),
    ('default-role-auxiliar-servicos-gerais', 'q-b5-ce-1'),
    ('default-role-auxiliar-servicos-gerais', 'q-b5-ce-2'),
    ('default-role-auxiliar-servicos-gerais', 'q-b5-ce-dial'),
    ('default-role-auxiliar-servicos-gerais', 'q-b1-detal-1'),
    ('default-role-auxiliar-servicos-gerais', 'q-b1-detal-2'),
    ('default-role-auxiliar-servicos-gerais', 'q-b1-detal-dial'),
    ('default-role-auxiliar-servicos-gerais', 'q-b1-agilidade-1'),
    ('default-role-auxiliar-servicos-gerais', 'q-b1-agilidade-2'),
    ('default-role-auxiliar-servicos-gerais', 'q-b1-agilidade-3'),
    ('default-role-auxiliar-servicos-gerais', 'q-b1-agilidade-4'),
    ('default-role-auxiliar-servicos-gerais', 'q-b1-agilidade-dial'),
    ('default-role-auxiliar-servicos-gerais', 'q-b4-com-1'),
    ('default-role-auxiliar-servicos-gerais', 'q-b4-com-2'),
    ('default-role-auxiliar-servicos-gerais', 'q-b4-com-3'),
    ('default-role-auxiliar-servicos-gerais', 'q-b4-com-dial'),
    ('role-1786309695980', 'q-b1-agilidade-1'),
    ('role-1786309695980', 'q-b1-agilidade-2'),
    ('role-1786309695980', 'q-b1-agilidade-3'),
    ('role-1786309695980', 'q-b1-agilidade-4'),
    ('role-1786309695980', 'q-b1-agilidade-dial'),
    ('role-1786309695980', 'q-b1-org-3'),
    ('role-1786309695980', 'q-b1-org-4'),
    ('role-1786309695980', 'q-b1-org-dial'),
    ('role-1786309695980', 'q-b1-detal-1'),
    ('role-1786309695980', 'q-b1-detal-2'),
    ('role-1786309695980', 'q-b1-detal-dial'),
    ('role-1786309695980', 'q-b2-rp-1'),
    ('role-1786309695980', 'q-b2-rp-2'),
    ('role-1786309695980', 'q-b2-rp-3'),
    ('role-1786309695980', 'q-b2-rp-dial'),
    ('role-1786309695980', 'q-b2-td-1'),
    ('role-1786309695980', 'q-b2-td-2'),
    ('role-1786309695980', 'q-b2-td-dial'),
    ('role-1786309695980', 'q-b4-com-1'),
    ('role-1786309695980', 'q-b4-com-2'),
    ('role-1786309695980', 'q-b4-com-3'),
    ('role-1786309695980', 'q-b4-com-dial'),
    ('role-1786309695980', 'q-b4-te-1'),
    ('role-1786309695980', 'q-b4-te-2'),
    ('role-1786309695980', 'q-b4-te-3'),
    ('role-1786309695980', 'q-b4-te-4'),
    ('role-1786309695980', 'q-b4-te-dial'),
    ('role-1786309695980', 'q-b4-ri-1'),
    ('role-1786309695980', 'q-b4-ri-2'),
    ('role-1786309695980', 'q-b4-ri-3'),
    ('role-1786309695980', 'q-b4-ri-dial'),
    ('role-1786309695980', 'q-b4-cor-1'),
    ('role-1786309695980', 'q-b4-cor-2'),
    ('role-1786309695980', 'q-b4-cor-dial'),
    ('role-1786309695980', 'q-b5-comp-1'),
    ('role-1786309695980', 'q-b5-comp-2'),
    ('role-1786309695980', 'q-b5-comp-dial'),
    ('role-1786309695980', 'q-b6-pd-1'),
    ('role-1786309695980', 'q-b6-pd-2'),
    ('role-1786309695980', 'q-b6-pd-dial'),
    ('role-1786309695980', 'q-b1-org-1'),
    ('role-1786309695980', 'q-b1-org-2'),
    ('role-1786310458988', 'q-b1-agilidade-1'),
    ('role-1786310458988', 'q-b1-agilidade-2'),
    ('role-1786310458988', 'q-b1-agilidade-3'),
    ('role-1786310458988', 'q-b1-agilidade-4'),
    ('role-1786310458988', 'q-b1-agilidade-dial'),
    ('role-1786310458988', 'q-b1-org-1'),
    ('role-1786310458988', 'q-b1-org-2'),
    ('role-1786310458988', 'q-b1-org-3'),
    ('role-1786310458988', 'q-b1-org-4'),
    ('role-1786310458988', 'q-b1-org-dial'),
    ('role-1786310458988', 'q-b1-prior-1'),
    ('role-1786310458988', 'q-b1-prior-2'),
    ('role-1786310458988', 'q-b1-prior-dial'),
    ('role-1786310458988', 'q-b1-detal-1'),
    ('role-1786310458988', 'q-b1-detal-2'),
    ('role-1786310458988', 'q-b1-detal-dial'),
    ('role-1786310458988', 'q-b2-rp-1'),
    ('role-1786310458988', 'q-b2-rp-2'),
    ('role-1786310458988', 'q-b2-rp-3'),
    ('role-1786310458988', 'q-b2-rp-dial'),
    ('role-1786310458988', 'q-b2-td-1'),
    ('role-1786310458988', 'q-b2-td-2'),
    ('role-1786310458988', 'q-b2-td-dial'),
    ('role-1786310458988', 'q-b3-fc-1'),
    ('role-1786310458988', 'q-b3-fc-2'),
    ('role-1786310458988', 'q-b3-fc-dial'),
    ('role-1786310458988', 'q-b3-np-1'),
    ('role-1786310458988', 'q-b3-np-2'),
    ('role-1786310458988', 'q-b3-np-dial'),
    ('role-1786310458988', 'q-b4-com-1'),
    ('role-1786310458988', 'q-b4-com-2'),
    ('role-1786310458988', 'q-b4-com-3'),
    ('role-1786310458988', 'q-b4-com-dial'),
    ('role-1786310458988', 'q-b4-te-1'),
    ('role-1786310458988', 'q-b4-te-2'),
    ('role-1786310458988', 'q-b4-te-3'),
    ('role-1786310458988', 'q-b4-te-4'),
    ('role-1786310458988', 'q-b4-te-dial'),
    ('role-1786310458988', 'q-b4-ri-1'),
    ('role-1786310458988', 'q-b4-ri-2'),
    ('role-1786310458988', 'q-b4-ri-3'),
    ('role-1786310458988', 'q-b4-ri-dial'),
    ('role-1786310458988', 'q-b5-comp-1'),
    ('role-1786310458988', 'q-b5-comp-2'),
    ('role-1786310458988', 'q-b5-comp-dial'),
    ('role-1786310458988', 'q-b5-ce-1'),
    ('role-1786310458988', 'q-b5-ce-2'),
    ('role-1786310458988', 'q-b5-ce-dial'),
    ('role-1786310458988', 'q-b5-conf-1'),
    ('role-1786310458988', 'q-b5-conf-2'),
    ('role-1786310458988', 'q-b5-conf-dial'),
    ('role-1786310458988', 'q-b6-af-1'),
    ('role-1786310458988', 'q-b6-af-2'),
    ('role-1786310458988', 'q-b6-af-dial'),
    ('role-1786310458988', 'q-b6-pd-1'),
    ('role-1786310458988', 'q-b6-pd-2'),
    ('role-1786310458988', 'q-b6-pd-dial'),
    ('role-1786310793425', 'q-b1-exec-1'),
    ('role-1786310793425', 'q-b1-exec-2'),
    ('role-1786310793425', 'q-b1-exec-3'),
    ('role-1786310793425', 'q-b1-exec-dial'),
    ('role-1786310793425', 'q-b1-org-1'),
    ('role-1786310793425', 'q-b1-org-2'),
    ('role-1786310793425', 'q-b1-org-3'),
    ('role-1786310793425', 'q-b1-org-4'),
    ('role-1786310793425', 'q-b1-org-dial'),
    ('role-1786310793425', 'q-b1-detal-1'),
    ('role-1786310793425', 'q-b1-detal-2'),
    ('role-1786310793425', 'q-b1-detal-dial'),
    ('role-1786310793425', 'q-b2-ra-1'),
    ('role-1786310793425', 'q-b2-ra-2'),
    ('role-1786310793425', 'q-b2-ra-dial'),
    ('role-1786310793425', 'q-b2-sc-1'),
    ('role-1786310793425', 'q-b2-sc-2'),
    ('role-1786310793425', 'q-b2-sc-dial'),
    ('role-1786310793425', 'q-b3-fc-1'),
    ('role-1786310793425', 'q-b3-fc-2'),
    ('role-1786310793425', 'q-b3-fc-dial'),
    ('role-1786310793425', 'q-b4-com-1'),
    ('role-1786310793425', 'q-b4-com-2'),
    ('role-1786310793425', 'q-b4-com-3'),
    ('role-1786310793425', 'q-b4-com-dial'),
    ('role-1786310793425', 'q-b4-ri-1'),
    ('role-1786310793425', 'q-b4-ri-2'),
    ('role-1786310793425', 'q-b4-ri-3'),
    ('role-1786310793425', 'q-b4-ri-dial'),
    ('role-1786310793425', 'q-b5-comp-1'),
    ('role-1786310793425', 'q-b5-comp-2'),
    ('role-1786310793425', 'q-b5-comp-dial'),
    ('role-1786310793425', 'q-b2-td-1'),
    ('role-1786310793425', 'q-b2-td-2'),
    ('role-1786310793425', 'q-b2-td-dial'),
    ('role-1786310793425', 'q-b3-np-1'),
    ('role-1786310793425', 'q-b3-np-2'),
    ('role-1786310793425', 'q-b3-np-dial'),
    ('role-1786312019898', 'q-b1-agilidade-1'),
    ('role-1786312019898', 'q-b1-agilidade-2'),
    ('role-1786312019898', 'q-b1-agilidade-3'),
    ('role-1786312019898', 'q-b1-agilidade-4'),
    ('role-1786312019898', 'q-b1-agilidade-dial'),
    ('role-1786312019898', 'q-b1-org-1'),
    ('role-1786312019898', 'q-b1-org-2'),
    ('role-1786312019898', 'q-b1-org-3'),
    ('role-1786312019898', 'q-b1-org-4'),
    ('role-1786312019898', 'q-b1-org-dial'),
    ('role-1786312019898', 'q-b1-detal-1'),
    ('role-1786312019898', 'q-b1-detal-2'),
    ('role-1786312019898', 'q-b1-detal-dial'),
    ('role-1786312019898', 'q-b3-fc-1'),
    ('role-1786312019898', 'q-b3-fc-2'),
    ('role-1786312019898', 'q-b3-fc-dial'),
    ('role-1786312019898', 'q-b3-np-1'),
    ('role-1786312019898', 'q-b3-np-2'),
    ('role-1786312019898', 'q-b3-np-dial'),
    ('role-1786312019898', 'q-b4-com-1'),
    ('role-1786312019898', 'q-b4-com-2'),
    ('role-1786312019898', 'q-b4-com-3'),
    ('role-1786312019898', 'q-b4-com-dial'),
    ('role-1786312019898', 'q-b4-te-1'),
    ('role-1786312019898', 'q-b4-te-2'),
    ('role-1786312019898', 'q-b4-te-3'),
    ('role-1786312019898', 'q-b4-te-4'),
    ('role-1786312019898', 'q-b4-te-dial'),
    ('role-1786312019898', 'q-b4-ri-1'),
    ('role-1786312019898', 'q-b4-ri-2'),
    ('role-1786312019898', 'q-b4-ri-3'),
    ('role-1786312019898', 'q-b4-ri-dial'),
    ('role-1786312019898', 'q-b5-comp-1'),
    ('role-1786312019898', 'q-b5-comp-2'),
    ('role-1786312019898', 'q-b5-comp-dial'),
    ('role-1786312019898', 'q-b5-ce-1'),
    ('role-1786312019898', 'q-b5-ce-2'),
    ('role-1786312019898', 'q-b5-ce-dial'),
    ('role-1786312019898', 'q-b6-pd-1'),
    ('role-1786312019898', 'q-b6-pd-2'),
    ('role-1786312019898', 'q-b6-pd-dial'),
    ('role-1786312019898', 'q-b4-di-1'),
    ('role-1786312019898', 'q-b4-di-2'),
    ('role-1786312019898', 'q-b4-di-dial'),
    ('role-1786312019898', 'q-b6-ac-1'),
    ('role-1786312019898', 'q-b6-ac-2'),
    ('role-1786312019898', 'q-b6-ac-dial'),
    ('role-1786312372107', 'q-b1-agilidade-1'),
    ('role-1786312372107', 'q-b1-agilidade-2'),
    ('role-1786312372107', 'q-b1-agilidade-3'),
    ('role-1786312372107', 'q-b1-agilidade-4'),
    ('role-1786312372107', 'q-b1-agilidade-dial'),
    ('role-1786312372107', 'q-b1-exec-1'),
    ('role-1786312372107', 'q-b1-exec-2'),
    ('role-1786312372107', 'q-b1-exec-3'),
    ('role-1786312372107', 'q-b1-exec-dial'),
    ('role-1786312372107', 'q-b1-org-1'),
    ('role-1786312372107', 'q-b1-org-2'),
    ('role-1786312372107', 'q-b1-org-3'),
    ('role-1786312372107', 'q-b1-org-4'),
    ('role-1786312372107', 'q-b1-org-dial'),
    ('role-1786312372107', 'q-b1-detal-1'),
    ('role-1786312372107', 'q-b1-detal-2'),
    ('role-1786312372107', 'q-b1-detal-dial'),
    ('role-1786312372107', 'q-b2-rl-1'),
    ('role-1786312372107', 'q-b2-rl-2'),
    ('role-1786312372107', 'q-b2-rl-3'),
    ('role-1786312372107', 'q-b2-rl-dial'),
    ('role-1786312372107', 'q-b2-ra-1'),
    ('role-1786312372107', 'q-b2-ra-2'),
    ('role-1786312372107', 'q-b2-ra-dial'),
    ('role-1786312372107', 'q-b2-sc-1'),
    ('role-1786312372107', 'q-b2-sc-2'),
    ('role-1786312372107', 'q-b2-sc-dial'),
    ('role-1786312372107', 'q-b2-rp-1'),
    ('role-1786312372107', 'q-b2-rp-2'),
    ('role-1786312372107', 'q-b2-rp-3'),
    ('role-1786312372107', 'q-b2-rp-dial'),
    ('role-1786312372107', 'q-b3-fc-1'),
    ('role-1786312372107', 'q-b3-fc-2'),
    ('role-1786312372107', 'q-b3-fc-dial'),
    ('role-1786312372107', 'q-b4-com-1'),
    ('role-1786312372107', 'q-b4-com-2'),
    ('role-1786312372107', 'q-b4-com-3'),
    ('role-1786312372107', 'q-b4-com-dial'),
    ('role-1786312372107', 'q-b4-te-1'),
    ('role-1786312372107', 'q-b4-te-2'),
    ('role-1786312372107', 'q-b4-te-3'),
    ('role-1786312372107', 'q-b4-te-4'),
    ('role-1786312372107', 'q-b4-te-dial'),
    ('role-1786312372107', 'q-b4-ri-1'),
    ('role-1786312372107', 'q-b4-ri-2'),
    ('role-1786312372107', 'q-b4-ri-3'),
    ('role-1786312372107', 'q-b4-ri-dial'),
    ('role-1786312372107', 'q-b5-resp-1'),
    ('role-1786312372107', 'q-b5-resp-2'),
    ('role-1786312372107', 'q-b5-resp-dial'),
    ('role-1786312372107', 'q-b5-conf-1'),
    ('role-1786312372107', 'q-b5-conf-2'),
    ('role-1786312372107', 'q-b5-conf-dial'),
    ('role-1786312372107', 'q-b5-trans-1'),
    ('role-1786312372107', 'q-b5-trans-2'),
    ('role-1786312372107', 'q-b5-trans-dial'),
    ('role-1786312372107', 'q-b6-ac-1'),
    ('role-1786312372107', 'q-b6-ac-2'),
    ('role-1786312372107', 'q-b6-ac-dial'),
    ('role-1786312372107', 'q-b6-af-1'),
    ('role-1786312372107', 'q-b6-af-2'),
    ('role-1786312372107', 'q-b6-af-dial'),
    ('role-1786312372107', 'q-b6-ad-1'),
    ('role-1786312372107', 'q-b6-ad-2'),
    ('role-1786312372107', 'q-b6-ad-dial'),
    ('role-1786312372107', 'q-b6-vf-1'),
    ('role-1786312372107', 'q-b6-vf-2'),
    ('role-1786312372107', 'q-b6-vf-dial'),
    ('role-1786312372107', 'q-b6-pd-1'),
    ('role-1786312372107', 'q-b6-pd-2'),
    ('role-1786312372107', 'q-b6-pd-dial'),
    ('role-1786312372107', 'q-b4-di-1'),
    ('role-1786312372107', 'q-b4-di-2'),
    ('role-1786312372107', 'q-b4-di-dial'),
    ('role-1786478528791', 'q-b1-agilidade-1'),
    ('role-1786478528791', 'q-b1-agilidade-2'),
    ('role-1786478528791', 'q-b1-agilidade-3'),
    ('role-1786478528791', 'q-b1-agilidade-dial'),
    ('role-1786478528791', 'q-b1-org-1'),
    ('role-1786478528791', 'q-b1-org-2'),
    ('role-1786478528791', 'q-b1-org-3'),
    ('role-1786478528791', 'q-b1-org-4'),
    ('role-1786478528791', 'q-b1-org-dial'),
    ('role-1786478528791', 'q-b1-detal-1'),
    ('role-1786478528791', 'q-b1-detal-2'),
    ('role-1786478528791', 'q-b1-detal-dial'),
    ('role-1786478528791', 'q-b2-ci-1'),
    ('role-1786478528791', 'q-b2-ci-2'),
    ('role-1786478528791', 'q-b2-ci-3'),
    ('role-1786478528791', 'q-b2-ci-dial'),
    ('role-1786478528791', 'q-b3-fc-1'),
    ('role-1786478528791', 'q-b3-fc-2'),
    ('role-1786478528791', 'q-b3-fc-dial'),
    ('role-1786478528791', 'q-b3-ac-1'),
    ('role-1786478528791', 'q-b3-ac-2'),
    ('role-1786478528791', 'q-b3-ac-dial'),
    ('role-1786478528791', 'q-b4-com-1'),
    ('role-1786478528791', 'q-b4-com-2'),
    ('role-1786478528791', 'q-b4-com-3'),
    ('role-1786478528791', 'q-b4-com-dial'),
    ('role-1786478528791', 'q-b4-te-1'),
    ('role-1786478528791', 'q-b4-te-2'),
    ('role-1786478528791', 'q-b4-te-3'),
    ('role-1786478528791', 'q-b4-te-4'),
    ('role-1786478528791', 'q-b4-te-dial'),
    ('role-1786478528791', 'q-b4-ri-1'),
    ('role-1786478528791', 'q-b4-ri-2'),
    ('role-1786478528791', 'q-b4-ri-3'),
    ('role-1786478528791', 'q-b4-ri-dial'),
    ('role-1786478528791', 'q-b4-cor-1'),
    ('role-1786478528791', 'q-b4-cor-2'),
    ('role-1786478528791', 'q-b4-cor-dial'),
    ('role-1786478528791', 'q-b4-di-1'),
    ('role-1786478528791', 'q-b4-di-2'),
    ('role-1786478528791', 'q-b4-di-dial'),
    ('role-1786478528791', 'q-b5-comp-1'),
    ('role-1786478528791', 'q-b5-comp-2'),
    ('role-1786478528791', 'q-b5-comp-dial'),
    ('role-1786478528791', 'q-b5-ce-1'),
    ('role-1786478528791', 'q-b5-ce-2'),
    ('role-1786478528791', 'q-b5-ce-dial'),
    ('role-1786478528791', 'q-b5-sig-1'),
    ('role-1786478528791', 'q-b5-sig-2'),
    ('role-1786478528791', 'q-b5-sig-dial'),
    ('role-1786478528791', 'q-b6-ac-1'),
    ('role-1786478528791', 'q-b6-ac-2'),
    ('role-1786478528791', 'q-b6-ac-dial'),
    ('role-1786478528791', 'q-b6-pd-1'),
    ('role-1786478528791', 'q-b6-pd-2'),
    ('role-1786478528791', 'q-b6-pd-dial');


  -- ---------------------------------------------------------------------
  -- Roles + activities
  -- ---------------------------------------------------------------------


  insert into roles (organization_id, name, type) values (v_org_id, '3D Manager', 'leadership') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('default-role-3d-manager', v_role_id, '3D Manager');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Integra os manuais de marca (brandbooks) aos projetos arquitetônicos, assegurando a aplicação correta de padrões gráficos, tipografia, cores e demais elementos visuais.', 0),
    (v_role_id, 'Desenvolve o Caderno de Arquitetura da Marca, documentando diretrizes técnicas para aplicação de comunicação visual e elementos decorativos nos espaços.', 1),
    (v_role_id, 'Desenvolve uma biblioteca de blocos, materiais, texturas e modelos 3D padronizados conforme as diretrizes da franquia.', 2),
    (v_role_id, 'Mantém organizada e atualizada a biblioteca de blocos, materiais, texturas e modelos 3D padronizados conforme as diretrizes da franquia.', 3),
    (v_role_id, 'Realiza interlocução com o cliente em conjunto com os coordenadores de projetos.', 4),
    (v_role_id, 'Identifica o contexto em que o projeto está inserido por meio da análise de mapas, imagens, vídeos e outras referências visuais relevantes.', 5),
    (v_role_id, 'Cria ambientes internos e externos em maquetes digitais a partir de conceitos visuais, utilizando softwares especializados como SketchUp, 3DS Max, Blender ou equivalentes.', 6),
    (v_role_id, 'Seleciona e sugere mobiliários, revestimentos, paletas de cores e elementos decorativos de acordo com a proposta criativa e as expectativas do cliente.', 7),
    (v_role_id, 'Projeta espaços em maquetes 3D, definindo mobiliários, revestimentos e paletas de cores que componham ambientes harmônicos e funcionais.', 8),
    (v_role_id, 'Produz imagens e vídeos realistas dos projetos por meio de técnicas avançadas de renderização, com foco em apresentação e impacto visual.', 9),
    (v_role_id, 'Aplica técnicas de pós-produção e edição de imagens para aprimorar a qualidade e a percepção visual dos projetos.', 10),
    (v_role_id, 'Desenvolve apresentações institucionais, materiais gráficos e banners para uso interno e externo, como palestras, eventos e reuniões comerciais.', 11),
    (v_role_id, 'Gerencia integralmente projetos selecionados, atuando de forma integrada com os coordenadores e demais membros da equipe.', 12),
    (v_role_id, 'Garante uniformidade visual e qualidade técnica dos materiais gráficos apresentados pela empresa, respeitando a identidade da marca.', 13),
    (v_role_id, 'Assume a liderança técnica de projetos quando necessário, coordenando o desenvolvimento visual e técnico das entregas.', 14),
    (v_role_id, 'Salva periodicamente os arquivos criados ou modificados na rede do escritório, assegurando organização e segurança das informações.', 15),
    (v_role_id, 'Treina estagiários na execução de projetos, modelagem 3D e demais atividades relacionadas à comunicação visual.', 16),
    (v_role_id, 'Fornece suporte ao desenvolvimento técnico e comportamental dos estagiários, promovendo integração à equipe.', 17),
    (v_role_id, 'Atualiza-se continuamente em inovações tecnológicas, participando de feiras, eventos e workshops da área.', 18);

  insert into roles (organization_id, name, type) values (v_org_id, 'Administrativo', 'collaborator') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('default-role-administrador', v_role_id, 'Administrativo');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Gerencia o ambiente organizacional de trabalho, assegurando a limpeza, a conservação da fachada e o funcionamento adequado da infraestrutura física do escritório.', 0),
    (v_role_id, 'Administra os processos administrativos gerais, incluindo a segurança patrimonial e a organização dos recursos operacionais.', 1),
    (v_role_id, 'Cadastra novos projetos nas plataformas de gestão utilizadas pelo escritório.', 2),
    (v_role_id, 'Gere a manutenção corretiva do escritório, acionando fornecedores e prestadores de serviço sempre que necessário.', 3),
    (v_role_id, 'Gere a manutenção preventiva do escritório, acionando fornecedores e prestadores de serviço conforme cronogramas e necessidades identificadas.', 4),
    (v_role_id, 'Organiza a agenda de eventos e atividades internas, como almoços, festas comemorativas, uso da sala de reuniões e envio de informes à equipe.', 5),
    (v_role_id, 'Administra os contratos dos colaboradores CLT, monitorando prazos, cláusulas e obrigações legais.', 6),
    (v_role_id, 'Realiza pesquisas internas voltadas ao bem-estar organizacional.', 7),
    (v_role_id, 'Conduz rodas de conversa no ambiente de trabalho, promovendo diálogo e escuta entre os colaboradores.', 8),
    (v_role_id, 'Promove eventos de integração entre os integrantes da equipe.', 9),
    (v_role_id, 'Conduz os processos de admissão de funcionários, conforme as diretrizes internas e a legislação trabalhista vigente.', 10),
    (v_role_id, 'Conduz os processos de desligamento de funcionários, conforme as diretrizes internas e a legislação trabalhista vigente.', 11),
    (v_role_id, 'Elabora contratos de trabalho e de prestação de serviços, conforme orientações e normas estabelecidas.', 12);

  insert into roles (organization_id, name, type) values (v_org_id, 'Desenvolvedor(a) de Projetos', 'collaborator') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('default-role-desenvolvedor-projetos', v_role_id, 'Desenvolvedor(a) de Projetos');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Colabora na elaboração e nos ajustes de layout em conjunto com franqueadoras e franqueados, contribuindo para soluções arquitetônicas alinhadas às diretrizes da marca.', 0),
    (v_role_id, 'Revisa todas as informações prévias do projeto, incluindo estudo preliminar, layout aprovado, imagens, vídeos do local, premissas, normas técnicas e legislação aplicável.', 1),
    (v_role_id, 'Participa de visitas técnicas, como levantamentos métricos, vistorias em lojas ou obras, sempre que solicitado.', 2),
    (v_role_id, 'Executa os projetos conforme os padrões técnicos e visuais previamente estabelecidos.', 3),
    (v_role_id, 'Produz as plantas dos projetos em desenvolvimento, incluindo cotas, níveis, especificações de materiais e indicações de detalhes construtivos.', 4),
    (v_role_id, 'Define materiais, acabamentos, esquadrias e mobiliários fixos, especificando marcas, modelos e padrões técnicos compatíveis com o projeto e com o cliente.', 5),
    (v_role_id, 'Elabora desenhos técnicos de detalhes construtivos, como paginação de pisos, forros, bancadas, guarda-corpos, sancas, marquises, entre outros.', 6),
    (v_role_id, 'Complementa os desenhos técnicos com informações precisas e coerentes com o escopo do projeto.', 7),
    (v_role_id, 'Elabora o memorial descritivo do projeto conforme orientações e diretrizes previamente estabelecidas pelo escritório.', 8),
    (v_role_id, 'Anexa o memorial descritivo do projeto na pasta específica da loja na rede interna.', 9),
    (v_role_id, 'Elabora a lista de compras de materiais e itens de obra, com referências, quantidades e fornecedores sugeridos, quando aplicável ao escopo.', 10),
    (v_role_id, 'Desenvolve cadernos técnicos de mobiliário, incluindo modelagem detalhada, especificações de materiais, instruções de montagem e acabamentos conforme exigências da franquia.', 11),
    (v_role_id, 'Desenvolve maquetes eletrônicas 3D com renderizações realistas, utilizando softwares compatíveis e atualizados.', 12),
    (v_role_id, 'Elabora apresentações visuais dos projetos para apresentação aos clientes, utilizando recursos gráficos e de modelagem alinhados à identidade visual do escritório.', 13),
    (v_role_id, 'Organiza, padroniza e disponibiliza os arquivos e documentos de projeto em formato adequado para obra (digital), incluindo imagens renderizadas e apresentações, conforme critérios internos.', 14),
    (v_role_id, 'Confere todas as peças gráficas e documentos do projeto antes da entrega, garantindo qualidade, consistência técnica e padronização visual.', 15),
    (v_role_id, 'Participa de reuniões de kickoff, presenciais ou on-line, contribuindo para o alinhamento técnico e a organização das etapas iniciais do projeto.', 16),
    (v_role_id, 'Submete o projeto executivo finalizado na rede interna de backup para validação da Coordenação de Projetos, atendendo aos prazos e requisitos estabelecidos.', 17),
    (v_role_id, 'Realiza adequações e correções no projeto a partir das devolutivas técnicas recebidas da Coordenação de Projetos.', 18),
    (v_role_id, 'Notifica os coordenadores sobre o avanço e a conclusão de cada etapa do desenvolvimento por meio da ferramenta de gestão de projetos.', 19),
    (v_role_id, 'Verifica periodicamente as notificações nas plataformas de trabalho utilizadas, garantindo acompanhamento e resposta às demandas em tempo hábil.', 20),
    (v_role_id, 'Colabora com as equipes de trabalho e diferentes departamentos, promovendo integração e fluidez na execução das atividades compartilhadas.', 21),
    (v_role_id, 'Participa de reuniões on-line e presenciais com foco em integração, feedback e alinhamento técnico.', 22),
    (v_role_id, 'Salva periodicamente os arquivos criados ou modificados na nuvem do escritório, garantindo segurança da informação e organização do material.', 23),
    (v_role_id, 'Salva e nomeia corretamente todos os arquivos e documentos conforme os padrões de nomenclatura definidos pelo escritório, garantindo uniformidade e rastreabilidade.', 24),
    (v_role_id, 'Disponibiliza o projeto completo no servidor do escritório, assegurando acesso da equipe à versão final atualizada e devidamente arquivada.', 25),
    (v_role_id, 'Aloca os materiais desenvolvidos nas pastas específicas de cada projeto na rede interna e comunica o status pela plataforma de gestão (ClickUp).', 26),
    (v_role_id, 'Atualiza-se continuamente em inovações tecnológicas, participando de feiras, eventos e workshops da área.', 27);

  insert into roles (organization_id, name, type) values (v_org_id, 'Financeiro', 'collaborator') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('default-role-financeiro', v_role_id, 'Financeiro');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Realiza a gestão de recebíveis junto aos clientes, acompanhando prazos e valores.', 0),
    (v_role_id, 'Administra as despesas fixas do condomínio e do escritório, como aluguel, água, energia, IPTU, internet, entre outras, respeitando prioridades e datas de vencimento.', 1),
    (v_role_id, 'Realiza os pagamentos de fornecedores e parceiros nas datas previstas, conforme os acordos estabelecidos.', 2),
    (v_role_id, 'Identifica inadimplências de clientes e parceiros, adotando medidas para regularização e manutenção da saúde financeira do escritório.', 3),
    (v_role_id, 'Garante o cumprimento das obrigações fiscais e tributárias, em conformidade com as exigências legais vigentes.', 4),
    (v_role_id, 'Gere o relacionamento com entidades externas, como bancos, contabilidade, prefeitura e advogados, prestando suporte administrativo sempre que necessário.', 5),
    (v_role_id, 'Atualiza os dados dos contratos na plataforma de gestão utilizada pelo escritório, mantendo o registro das etapas sempre atualizado.', 6),
    (v_role_id, 'Confere o recebimento dos arquivos editáveis dos projetos antes de liberar pagamentos para as equipes envolvidas.', 7),
    (v_role_id, 'Acompanha todo o ciclo dos projetos nas plataformas de gestão, desde a formalização do contrato até a entrega final ao cliente.', 8);

  insert into roles (organization_id, name, type) values (v_org_id, 'Gestor de Obra', 'leadership') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('default-role-gestor-obra', v_role_id, 'Gestor de Obra');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Mantém-se atualizado em relação aos manuais e diretrizes das franquias atendidas, aplicando corretamente suas exigências durante a execução das obras.', 0),
    (v_role_id, 'Analisa os projetos antes do início do acompanhamento de obra, verificando diretrizes, premissas e particularidades técnicas.', 1),
    (v_role_id, 'Participa de reuniões de kickoff e de alinhamento para adequações de projeto ao longo da execução da obra.', 2),
    (v_role_id, 'Intermedeia ajustes e conflitos relacionados ao escopo do projeto, propondo soluções técnicas e viáveis.', 3),
    (v_role_id, 'Mede e analisa ajustes e conflitos relacionados ao escopo do projeto, propondo soluções técnicas compatíveis com a execução da obra.', 4),
    (v_role_id, 'Fornece feedback técnico aos projetistas para aprimoramento de detalhes de projeto, quando identifica falhas ou informações insuficientes.', 5),
    (v_role_id, 'Confere cotações de orçamentos e quantitativos em relação aos projetos, garantindo precisão e aderência nas contratações.', 6),
    (v_role_id, 'Solicita ajustes quando identifica incompatibilidades entre o projeto e as condições reais do espaço físico.', 7),
    (v_role_id, 'Avalia a necessidade de revisões ou novas aprovações junto aos projetistas ao longo do processo de execução.', 8),
    (v_role_id, 'Responde dúvidas técnicas da equipe de obra relacionadas aos projetos e à execução.', 9),
    (v_role_id, 'Registra feedbacks na plataforma de gestão de projetos e acompanha o andamento das obras via WhatsApp, garantindo alinhamento com os projetos desenvolvidos.', 10),
    (v_role_id, 'Cobra empreiteiros pelo envio de fotos e vídeos do andamento e da conclusão das obras, conforme cronograma estabelecido.', 11),
    (v_role_id, 'Gere o relacionamento com fornecedores, franqueadores e franqueados durante o processo de obra.', 12),
    (v_role_id, 'Atua como ponto de contato entre a equipe interna, franqueadora, franqueado e fornecedores em todas as etapas do projeto.', 13),
    (v_role_id, 'Comunica-se de forma contínua com os responsáveis pelo projeto e com a equipe de obra, assegurando alinhamento técnico e operacional.', 14),
    (v_role_id, 'Preenche o checklist final de conformidades conforme os padrões da franqueadora e do projeto antes da conclusão da obra.', 15);

  insert into roles (organization_id, name, type) values (v_org_id, 'Gerente Comercial', 'leadership') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('default-role-gerente-comercial', v_role_id, 'Gerente Comercial');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Prospecta ativamente novos clientes e contratos por meio de networking, visitas comerciais e ligações telefônicas estratégicas.', 0),
    (v_role_id, 'Mantém contato com stakeholders em nível nacional e internacional, identificando oportunidades comerciais e tendências de mercado.', 1),
    (v_role_id, 'Presta suporte aos clientes (franqueador e franqueado) por telefone, e-mail e demais canais de comunicação.', 2),
    (v_role_id, 'Negocia com os clientes novos contratos, prazos, entregas, orçamentos e o funcionamento do modelo de trabalho, assegurando alinhamento entre as partes.', 3),
    (v_role_id, 'Conduz reuniões iniciais de alinhamento com os clientes e a equipe de projeto, garantindo compatibilidade entre as expectativas comerciais e o escopo técnico do projeto.', 4),
    (v_role_id, 'Desenvolve propostas comerciais personalizadas em conjunto com a equipe de gestão.', 5),
    (v_role_id, 'Acompanha as aprovações de propostas e contratos de prestação de serviço por meio da plataforma de gestão, assegurando o fluxo correto do processo comercial.', 6),
    (v_role_id, 'Define a composição de preços, estimando custos por projeto, consultorias e honorários, garantindo equilíbrio entre competitividade e rentabilidade.', 7),
    (v_role_id, 'Filtra clientes em potencial por meio de reuniões e pesquisas de mercado, assegurando alinhamento estratégico, rentabilidade e compatibilidade com os valores do escritório.', 8),
    (v_role_id, 'Desenvolve e aprimora continuamente os processos comerciais a partir do mapeamento das etapas de atendimento e vendas, identificando gargalos e oportunidades de melhoria.', 9),
    (v_role_id, 'Realiza análises periódicas de mercado e concorrência (mensais e trimestrais), ajustando campanhas, posicionamento e ofertas com base nos dados coletados.', 10),
    (v_role_id, 'Propõe melhorias contínuas nos processos, estratégias e desempenho financeiro a partir dos resultados comerciais obtidos.', 11),
    (v_role_id, 'Participa de, no mínimo, dois eventos por ano (como Expo Revestir, ABF, Casa Cor SP, NFR, NRA e convenções), com foco em atualização profissional e ampliação de networking estratégico.', 12),
    (v_role_id, 'Avalia a satisfação dos clientes por meio do formulário NPS (Net Promoter Score).', 13),
    (v_role_id, 'Envia formulário cadastral aos clientes para coleta de dados essenciais à formalização e à execução dos projetos.', 14);

  insert into roles (organization_id, name, type) values (v_org_id, 'Coordenador(a) de Projetos', 'leadership') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('default-role-coordenadora-projetos', v_role_id, 'Coordenador(a) de Projetos');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Realiza o onboarding técnico de estagiários e profissionais recém-contratados.', 0),
    (v_role_id, 'Delega tarefas compatíveis com o nível de experiência de cada integrante da equipe, supervisionando prazos e qualidade das entregas.', 1),
    (v_role_id, 'Fornece feedbacks técnicos e comportamentais periódicos aos integrantes da equipe.', 2),
    (v_role_id, 'Apoia decisões internas relacionadas à gestão da equipe, organização de demandas e melhoria de processos.', 3),
    (v_role_id, 'Registra as necessidades específicas de cada projeto e as expectativas do cliente durante as reuniões de kickoff na plataforma de gestão ClickUp.', 4),
    (v_role_id, 'Realiza o primeiro contato com o cliente franqueado.', 5),
    (v_role_id, 'Garante disponibilidade para comunicação com o cliente via WhatsApp em todas as fases do projeto, assegurando o esclarecimento de dúvidas.', 6),
    (v_role_id, 'Coordena as tarefas executadas pelos integrantes dos projetos.', 7),
    (v_role_id, 'Supervisiona o envio dos arquivos em formato XLS dos projetos aprovados pela franqueadora.', 8),
    (v_role_id, 'Recebe os projetos aprovados, organiza e preenche a planilha de controle de projetos.', 9),
    (v_role_id, 'Colabora com engenheiros, construtores e fornecedores para garantir a viabilidade técnica dos projetos, assegurando a compatibilização adequada das informações.', 10),
    (v_role_id, 'Aloca as demandas dos projetos aprovados aos integrantes da equipe de desenvolvedores de projetos.', 11),
    (v_role_id, 'Gera e gerencia os cronogramas dos projetos no ClickUp, controlando prazos e demandas.', 12),
    (v_role_id, 'Registra e devolve as modificações necessárias aos desenvolvedores responsáveis pelos projetos.', 13),
    (v_role_id, 'Revisa e orienta as correções dos projetos em desenvolvimento junto aos arquitetos responsáveis até que atinjam o padrão adequado.', 14),
    (v_role_id, 'Realiza interlocuções técnicas com franqueadoras e franqueados para garantir alinhamento técnico e conceitual dos projetos, assegurando conformidade com os padrões exigidos.', 15),
    (v_role_id, 'Levanta as necessidades específicas de cada projeto e as expectativas de cada cliente a partir das reuniões de kickoff.', 16),
    (v_role_id, 'Computa e organiza todos os dados de entrada dos projetos, incluindo manual de franquia, caderno de normas técnicas e diretrizes de layout padrão.', 17),
    (v_role_id, 'Mantém o cliente atualizado sobre o andamento dos projetos.', 18),
    (v_role_id, 'Realiza contato com fornecedores para esclarecimento de dúvidas técnicas ou projetuais quando necessário (elétrica, hidráulica, entre outras).', 19),
    (v_role_id, 'Envia e acompanha os projetos junto ao franqueado, franqueadora ou concessionárias (aeroportos, shoppings, galerias, entre outros).', 20),
    (v_role_id, 'Desenvolve o layout inicial dos projetos propostos, considerando possíveis dificuldades e detalhes construtivos.', 21),
    (v_role_id, 'Envia o layout do projeto proposto para aprovação do cliente.', 22),
    (v_role_id, 'Participa do comitê de projetos com a ZAMP, responsável pela marca Subway no Brasil.', 23),
    (v_role_id, 'Confere dimensões, itens da lista de compras, Memorial Descritivo e RRT dos projetos antes da entrega final.', 24);

  insert into roles (organization_id, name, type) values (v_org_id, 'Auxiliar de Serviços Gerais', 'collaborator') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('default-role-auxiliar-servicos-gerais', v_role_id, 'Auxiliar de Serviços Gerais');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Executa a limpeza seguindo uma rotina definida, garantindo padrão de higiene em todos os ambientes, incluindo o depósito de materiais de limpeza e as superfícies.', 0),
    (v_role_id, 'Manuseia adequadamente equipamentos, móveis, cortinas e utensílios do escritório durante a limpeza.', 1),
    (v_role_id, 'Mantém a copa e a cozinha limpas e organizadas, garantindo que pia, bancadas, armários, geladeiras, eletrodomésticos e resíduos estejam em seus locais corretos.', 2),
    (v_role_id, 'Realiza a limpeza e a manutenção básica do quintal e das áreas externas, incluindo varrição, retirada de folhas, limpeza de áreas pavimentadas, rega de plantas e retirada de galhos secos.', 3),
    (v_role_id, 'Realiza a coleta e o descarte correto do lixo, seguindo as orientações de separação e reciclagem.', 4),
    (v_role_id, 'Informa com antecedência à administração sobre a necessidade de reposição dos materiais de limpeza.', 5),
    (v_role_id, 'Reposição materiais de higiene, como papel higiênico, papel toalha, sabonete, entre outros, sempre que necessário.', 6),
    (v_role_id, 'Utiliza produtos e materiais adequados para cada tipo de superfície, preservando sua conservação.', 7),
    (v_role_id, 'Troca e lava copos e xícaras das salas sempre que necessário.', 8),
    (v_role_id, 'Lava adequadamente e diariamente as vasilhas de água das cachorras.', 9),
    (v_role_id, 'Troca a água das cachorras com frequência, garantindo que esteja sempre limpa e fresca.', 10),
    (v_role_id, 'Verifica a presença de fezes das cachorras nas áreas internas ou externas do escritório, avisando imediatamente a pessoa responsável (Camila ou Luís) e realizando o descarte quando necessário.', 11),
    (v_role_id, 'Apoia na preparação de ambientes para reuniões ou eventos internos, conforme orientações recebidas.', 12),
    (v_role_id, 'Lava itens seguindo os procedimentos e rotinas estabelecidas.', 13),
    (v_role_id, 'Apoia no preparo de refeições simples, realizando tarefas básicas sob orientação.', 14);

  insert into roles (organization_id, name, type) values (v_org_id, 'Analista de Projetos', 'collaborator') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('role-1786309695980', v_role_id, 'Analista de Projetos');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Realizar a análise técnica dos projetos desenvolvidos, com base nos critérios, padrões e diretrizes definidos para cada entrega', 0),
    (v_role_id, 'Aplicar check-list técnico de conferência, em formato on-line e/ou físico, para verificar a conformidade dos projetos antes da liberação', 1),
    (v_role_id, 'Identificar inconsistências, não conformidades e necessidades de ajuste nos projetos analisados', 2),
    (v_role_id, 'Encaminhar solicitações de correção e adequação aos responsáveis pelos projetos, com base nos apontamentos identificados durante a análise', 3),
    (v_role_id, 'Contribuir para o alinhamento técnico entre projetistas, gestão de projetos e demais envolvidos, sempre que necessário ao andamento das análises', 4),
    (v_role_id, 'Manter atualizadas no Click Up as informações relacionadas ao andamento das análises, revisões e liberações para desenvolvedor e coordenador de projetos', 5),
    (v_role_id, 'Participar, quando houver convite ou necessidade vinculada às demandas em andamento, de reuniões de alinhamento ou treinamento com a equipe', 6),
    (v_role_id, 'Acompanhar e estudar os guides, padrões e materiais de referência das franquias, com o objetivo de manter a qualidade técnica das análises e a atualização dos critérios aplicáveis', 7),
    (v_role_id, 'Fornecer feedbacks técnicos e comportamentais periódicos aos integrantes envolvidos nos projetos', 8);

  insert into roles (organization_id, name, type) values (v_org_id, 'Administrativo/ Financeiro / Gestão de Obras', 'collaborator') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('role-1786310458988', v_role_id, 'Administrativo/ Financeiro / Gestão de Obras');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Gerenciar o ambiente organizacional de trabalho, assegurando a manutenção da limpeza, conservação da fachada e funcionamento adequado da infraestrutura física do escritório.', 0),
    (v_role_id, 'Administrar os processos administrativos gerais, incluindo a segurança patrimonial e a organização dos recursos operacionais.', 1),
    (v_role_id, 'Gerir a manutenção corretiva do escritório, acionando fornecedores e prestadores de serviço quando necessário.', 2),
    (v_role_id, 'Gerir a manutenção preventiva do escritório, acionando fornecedores e prestadores de serviço quando necessário.', 3),
    (v_role_id, 'Organizar a agenda de eventos e atividades internas, como almoços, festas comemorativas, uso da sala de reunião e envio de informes à equipe.', 4),
    (v_role_id, 'Administrar os contratos dos colaboradores CLT, monitorando prazos, cláusulas e obrigações legais.', 5),
    (v_role_id, 'Promover eventos de integração da equipe.', 6),
    (v_role_id, 'Realizar os processos de admissão de funcionários, conforme as diretrizes internas e a legislação trabalhista vigente.', 7),
    (v_role_id, 'Conduzir os processos de desligamento de funcionários e parceiros, conforme as diretrizes internas e a legislação trabalhista vigente.', 8),
    (v_role_id, 'Elaborar contratos de trabalho e prestação de serviços.', 9),
    (v_role_id, 'Coordenar o fluxo das atividades prestadas no apoio administrativo, financeiro e operacional, acompanhando a qualidade das entregas, a atualização das informações e o andamento das demandas relacionadas aos serviços contratados', 10),
    (v_role_id, 'Realizar a gestão dos recebíveis junto aos clientes, acompanhando os valores a receber e o andamento das cobranças', 11),
    (v_role_id, 'Administrar as despesas fixas do condomínio e do escritório, observando prioridades, vencimentos e necessidades de pagamento', 12),
    (v_role_id, 'Executar os pagamentos de fornecedores e parceiros conforme os acordos estabelecidos e os prazos aplicáveis', 13),
    (v_role_id, 'Identificar situações de inadimplência de clientes e parceiros, adotando as medidas cabíveis para regularização e acompanhamento financeiro', 14),
    (v_role_id, 'Acompanhar o cumprimento das obrigações fiscais e tributárias aplicáveis, em alinhamento com as exigências legais e com os prestadores responsáveis', 15),
    (v_role_id, 'Conduzir o relacionamento com entidades externas, como bancos, contabilidade, prefeitura, assessorias e demais parceiros relacionados às demandas financeiras e administrativas', 16),
    (v_role_id, 'Inserir os dados contratuais e registros das etapas dos projetos na plataforma click-up', 17),
    (v_role_id, 'Coordenar o fluxo das atividades prestadas no apoio financeiro e operacional, acompanhando a qualidade das entregas, a atualização das informações e o andamento das demandas relacionadas aos serviços contratados', 18),
    (v_role_id, 'Manter-se atualizado em relação aos manuais e diretrizes das franquias atendidas, aplicando corretamente suas exigências', 19),
    (v_role_id, 'Analisar os projetos antes do início do acompanhamento da obra, verificando suas diretrizes e particularidades', 20),
    (v_role_id, 'Participar de reuniões de kickoff e de alinhamento para adaptações de projeto ao longo da execução da obra', 21),
    (v_role_id, 'Intermediar ajustes e conflitos relacionados ao escopo do projeto, buscando soluções técnicas e viáveis', 22),
    (v_role_id, 'Fornecer feedback técnico ao projetista para melhorias em detalhes de projeto, quando identificar falhas ou informações insuficientes', 23),
    (v_role_id, 'Conferir as cotações de orçamentos e quantitativos em relação aos projetos, garantindo precisão nas contratações', 24),
    (v_role_id, 'Solicitar ajustes de incompatibilidades entre o projeto e as condições reais do espaço físico, quando necessário', 25),
    (v_role_id, 'Avaliar a necessidade de revisões ou aprovações com os projetistas ao longo do processo de execução', 26),
    (v_role_id, 'Responder dúvidas técnicas da equipe de obra relacionadas aos projetos e à execução da obra', 27),
    (v_role_id, 'Registrar feedbacks no PNR e acompanhar o andamento das obras via WhatsApp, garantindo alinhamento com os projetos desenvolvidos', 28),
    (v_role_id, 'Gerir o relacionamento com fornecedores e franqueados', 29),
    (v_role_id, 'Atuar como ponto de contato entre a equipe interna, o franqueado e os fornecedores durante todas as etapas do projeto', 30),
    (v_role_id, 'Preencher o checklist de conformidades conforme a execução do projeto', 31);

  insert into roles (organization_id, name, type) values (v_org_id, 'Digitalização', 'collaborator') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('role-1786310793425', v_role_id, 'Digitalização');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Receber e analisar as informações iniciais da unidade franqueada incluindo dados da loja, padrão atual de decoração, plantas existentes, fotos, documentos técnicos e demais materiais disponíveis.', 0),
    (v_role_id, 'Comparar o projeto existente com as diretrizes atualizadas da franqueadora.', 1),
    (v_role_id, 'Mapear os ajustes necessários para enquadramento no plano de remodelação.', 2),
    (v_role_id, 'Organizar as informações do projeto em software técnico adequado.', 3),
    (v_role_id, 'Propor soluções de adequação compatíveis com o padrão da marca e a realidade da loja.', 4),
    (v_role_id, 'Preparar materiais para apresentação em reunião de comitê.', 5),
    (v_role_id, 'Apresentar a proposta de adequação para análise e aprovação.', 6),
    (v_role_id, 'Revisar e ajustar o projeto conforme apontamentos recebidos.', 7),
    (v_role_id, 'Colaborar com as equipes de trabalho e diferentes departamentos, promovendo integração e fluidez na execução das atividades compartilhadas', 8),
    (v_role_id, 'Participar de reuniões on-line e presenciais com o objetivo de integração, feedback e alinhamento', 9),
    (v_role_id, 'Salvar periodicamente os arquivos criados ou modificados na nuvem de arquivos do escritório, garantindo segurança da informação e organização do material', 10),
    (v_role_id, 'Atualizar-se constantemente em inovações tecnológicas, com participação em feiras, eventos e workshops da área', 11),
    (v_role_id, 'Gerir o relacionamento com franqueados, respondendo dúvidas e se colocando à disposição.', 12);

  insert into roles (organization_id, name, type) values (v_org_id, 'Auxiliar Administrativo Financeiro / Gestão de Obras', 'collaborator') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('role-1786312019898', v_role_id, 'Auxiliar Administrativo Financeiro / Gestão de Obras');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Prestar apoio às demandas administrativas, financeiras e de organização de informações relacionadas às atividades do escritório', 0),
    (v_role_id, 'Organizar documentos físicos e digitais vinculados a processos administrativos, financeiros, contratuais e de apoio à operação', 1),
    (v_role_id, 'Atualizar planilhas, sistemas e plataformas de gestão com informações administrativas, financeiras e operacionais', 2),
    (v_role_id, 'Acompanhar prazos, pendências e vencimentos relacionados às demandas sob sua atuação, comunicando necessidades de andamento aos pontos de contato definidos', 3),
    (v_role_id, 'Solicitar documentos, comprovantes e informações complementares a colaboradores, fornecedores, parceiros, prestadores e demais envolvidos, sempre que necessário ao andamento das atividades', 4),
    (v_role_id, 'Contribuir para o controle de pagamentos, recebimentos e despesas por meio da organização das informações e da conferência dos dados lançados', 5),
    (v_role_id, 'Atualizar dados contratuais, operacionais e de andamento dos projetos nas plataformas de gestão utilizadas pelo escritório', 6),
    (v_role_id, 'Prestar apoio à organização de entrevistas, reuniões, comunicações e demais ações relacionadas à dinâmica interna e à gestão de pessoas', 7),
    (v_role_id, 'Realizar atendimento a franqueados, prestando informações, encaminhando solicitações e direcionando dúvidas relacionadas ao ciclo dos projetos', 8),
    (v_role_id, 'Realizar contatos, repasses de informações e acompanhamentos com fornecedores, conforme a necessidade das demandas em andamento', 9),
    (v_role_id, 'Encaminhar dúvidas técnicas da equipe de obras aos responsáveis pelos projetos, acompanhando o retorno necessário para continuidade do fluxo', 10),
    (v_role_id, 'Realizar cotações de orçamentos e levantamentos quantitativos relacionados aos projetos, conforme a demanda de cada etapa', 11),
    (v_role_id, 'Organizar e enviar aos franqueados cotações, orçamentos e informações sobre fornecedores de materiais, conforme os alinhamentos definidos para cada projeto', 12),
    (v_role_id, 'Prestar apoio à organização de eventos, confraternizações e ações internas promovidas pelo escritório', 13);

  insert into roles (organization_id, name, type) values (v_org_id, 'Estagiário(a) Desenvolvimento de Projetos', 'collaborator') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('role-1786312372107', v_role_id, 'Estagiário(a) Desenvolvimento de Projetos');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Aplicar as diretrizes da franquia nos projetos, assegurando coerência técnica e estética com os padrões exigidos pela marca.', 0),
    (v_role_id, 'Criar imagens realistas (renders) das fachadas e ambientes internos dos projetos utilizando softwares específicos como SketchUp, IA e similares.', 1),
    (v_role_id, 'Pesquisar e se atualizar constantemente sobre arquitetura para varejo, franquias e outras áreas correlatas, visando a inovação e o aprimoramento técnico.', 2),
    (v_role_id, 'Aplicar as exigências técnicas de cada franquia nos projetos desenvolvidos.', 3),
    (v_role_id, 'Desenvolver projetos que possuam padrões repetitivos de detalhes construtivos e acabamentos, apresentando-os ao supervisor para validação.', 4),
    (v_role_id, 'Executar os projetos com boa diagramação e conforme os padrões gráficos definidos pelo escritório.                                ', 5),
    (v_role_id, 'Salvar periodicamente os arquivos criados ou modificados na rede do escritório, assegurando backup.', 6),
    (v_role_id, 'Responder comunicação via WhatsApp e plataforma interna.', 7),
    (v_role_id, 'Manter atualizadas as informações nas plataformas de gerenciamento de projetos.', 8),
    (v_role_id, 'Participar de reuniões internas de planejamento e avaliação quando necessário.', 9),
    (v_role_id, 'Contribuir com informações técnicas sempre que necessário.', 10);

  insert into roles (organization_id, name, type) values (v_org_id, 'Estagiário(a) - Gestão de Projetos', 'collaborator') returning id into v_role_id;
  insert into tmp_roles (json_id, role_id, name) values ('role-1786478528791', v_role_id, 'Estagiário(a) - Gestão de Projetos');
  insert into role_activities (role_id, text, "order") values
    (v_role_id, 'Receber as demandas iniciais de projetos já contratados e organizar as informações recebidas para início do fluxo interno.', 0),
    (v_role_id, 'Realizar contatos iniciais com clientes, conforme orientação da PMO, para solicitar, confirmar e registrar informações, documentos e materiais necessários ao início do projeto.', 1),
    (v_role_id, 'Conferir se a documentação, os dados e os materiais de entrada do projeto estão completos para continuidade do processo.', 2),
    (v_role_id, 'Identificar e solicitar pendências de informações, documentos ou definições necessárias para abertura e andamento do projeto.', 3),
    (v_role_id, 'Apoiar na atualização do status dos projetos no ClickUp, garantindo visibilidade sobre etapa, responsável e pendências.', 4),
    (v_role_id, 'Alocar os documentos e materiais dos projetos nos locais corretos, garantindo organização e fácil rastreabilidade.', 5),
    (v_role_id, 'Cumprir os padrões internos de organização, nomenclatura, registro e controle de projetos adotados pelo escritório.', 6),
    (v_role_id, 'Compatibilizar imagens com levantamento recebidos;', 7),
    (v_role_id, 'Estudar os cadernos técnicos da franquia e dos fornecedores, a fim de realizar análises de levantamento conforme os padrões da marca.', 8),
    (v_role_id, 'Analisar e aprovar os checklists de levantamento das lojas no PNR.', 9),
    (v_role_id, 'Baixar os arquivos necessários no PNR para executar a análise do material enviado, comparando desenhos com fotos e vídeos para verificar a coerência do levantamento com a realidade da loja.', 10),
    (v_role_id, 'Realizar contato com o cliente via WhatsApp, quando houver reprovação do levantamento, para esclarecer dúvidas, orientar o franqueado e solicitar o reenvio correto das informações, conforme o fluxo definido.', 11),
    (v_role_id, 'Responder às dúvidas da equipe sobre o status dos projetos, quando solicitado, por meio do ClickUp.', 12),
    (v_role_id, 'Criar e organizar as pastas das lojas na rede.', 13),
    (v_role_id, 'Solicitar, acompanhar, baixar do Drive e salvar os arquivos Fullset nas pastas correspondentes de cada loja na rede.', 14),
    (v_role_id, 'Gerar arquivos em PDF dos materiais Fullset e armazená-los nas pastas das lojas.', 15),
    (v_role_id, 'Responder às dúvidas dos franqueados por e-mail e WhatsApp.', 16),
    (v_role_id, 'Acompanhar os pedidos de correção de levantamento e cobrar os retornos necessários, quando aplicável.', 17);

  -- ---------------------------------------------------------------------
  -- role_competencies: aggregate selected question ids per (role, competency)
  -- from the role's flat questionIds list.
  -- ---------------------------------------------------------------------
  insert into role_competencies (role_id, competency_id, selected_question_ids)
  select tr.role_id, m.competency_id, array_agg(distinct m.question_id)
  from tmp_role_questions rq
  join tmp_roles tr on tr.json_id = rq.role_json_id
  join tmp_qmap m on m.json_qid = rq.json_qid
  group by tr.role_id, m.competency_id;

  -- ---------------------------------------------------------------------
  -- Members — role_id resolved by matching member.position to role.name
  -- (exact match in the export; verified 1:1 against roles above).
  -- ---------------------------------------------------------------------

  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Luís', 'Tortola', '1983-04-26', 'day', '2014-01-01', 'day', (select role_id from tmp_roles where name = 'Gerente Comercial'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Camila', 'Coutinho', '1985-08-30', 'day', null, null, (select role_id from tmp_roles where name = 'Coordenador(a) de Projetos'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Luan', 'Rodrigo Frantz', '1992-06-20', 'day', null, null, (select role_id from tmp_roles where name = 'Desenvolvedor(a) de Projetos'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Heiron', 'Douglas Soares', '1998-04-06', 'day', null, null, (select role_id from tmp_roles where name = 'Desenvolvedor(a) de Projetos'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Pedro', 'Henrique Potenciano', '1998-08-03', 'day', null, null, (select role_id from tmp_roles where name = 'Desenvolvedor(a) de Projetos'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Nathália', 'Ribeiro', '1990-01-06', 'day', null, null, (select role_id from tmp_roles where name = 'Coordenador(a) de Projetos'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Ingrid', 'Freire', '1992-02-06', 'day', null, null, (select role_id from tmp_roles where name = 'Coordenador(a) de Projetos'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Dayane', 'Vieira da Silva', '1985-11-08', 'day', null, null, (select role_id from tmp_roles where name = 'Coordenador(a) de Projetos'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Nelly', 'Fernanda Tortola', '1980-03-11', 'day', null, null, (select role_id from tmp_roles where name = 'Administrativo/ Financeiro / Gestão de Obras'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Matheus', 'Faleiro', '2000-03-12', 'day', null, null, (select role_id from tmp_roles where name = 'Desenvolvedor(a) de Projetos'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Deborah', 'Lorrayne Souza', '2001-07-27', 'day', '2016-08-03', 'day', (select role_id from tmp_roles where name = 'Coordenador(a) de Projetos'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Isabelle', 'Peixoto', '1999-08-10', 'day', '2026-04-22', 'day', (select role_id from tmp_roles where name = 'Desenvolvedor(a) de Projetos'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Gabriela', 'Sabatini', '1997-03-11', 'day', '2026-04-22', 'day', (select role_id from tmp_roles where name = 'Desenvolvedor(a) de Projetos'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Rafael', 'Adorno', '1995-03-22', 'day', '2026-04-22', 'day', (select role_id from tmp_roles where name = 'Desenvolvedor(a) de Projetos'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Letizia', 'Pecorone', '1998-01-30', 'day', '2026-04-22', 'day', (select role_id from tmp_roles where name = 'Desenvolvedor(a) de Projetos'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Allan', 'Pedro Laet Silva', '1993-12-19', 'day', null, null, (select role_id from tmp_roles where name = 'Digitalização'));
  insert into members (organization_id, first_name, last_name, birth_date, birth_date_precision, start_date, start_date_precision, role_id)
  values (v_org_id, 'Yasmin', 'Ferreira Barros', '2003-10-24', 'day', '2026-05-04', 'day', (select role_id from tmp_roles where name = 'Estagiário(a) Desenvolvimento de Projetos'));

end $$;
